/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef TYPES_H
#define TYPES_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"

typedef struct {
    uint32_t _maximum;
    uint32_t _length;
    int32_t *_buffer;
    bool _release;
} int32_t_seq;

typedef enum {
    Color_RED = 0,
    Color_GREEN = 1,
    Color_BLUE = 2
} Color;

typedef struct Point_s {
    int32_t x;
    int32_t y;
} Point;

#define Point_has_key 0
int Point_serialize(ZidlCdrWriter *_w, const Point *_v);
int Point_deserialize(ZidlCdrReader *_r, Point *_v);
int Point_skip(ZidlCdrReader *_r);

typedef struct Sample_s {
    uint32_t id;
    bool b;
    uint8_t u8_val;
    int16_t s16_val;
    uint16_t u16_val;
    int32_t s32_val;
    uint32_t u32_val;
    int64_t s64_val;
    uint64_t u64_val;
    float f32_val;
    double f64_val;
    char *str;
    char bstr[33];
    int32_t_seq nums;
    int32_t arr[3];
    Color clr;
    Point nested;
} Sample;

#define Sample_has_key 1
int Sample_serialize(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize(ZidlCdrReader *_r, Sample *_v);
int Sample_skip(ZidlCdrReader *_r);
int Sample_serialize_key(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize_key(ZidlCdrReader *_r, Sample *_v);
int Sample_compute_key_hash(const Sample *_v, uint8_t _hash[16]);

typedef struct Frame_s {
    uint32_t seq_num;
    char *topic;
} Frame;

#define Frame_has_key 0
int Frame_serialize(ZidlCdrWriter *_w, const Frame *_v);
int Frame_deserialize(ZidlCdrReader *_r, Frame *_v);
int Frame_skip(ZidlCdrReader *_r);

/* IDL interface: Greeter */
typedef struct Greeter_Vtable {
    char *(*greet)(void *ptr, char *name);
    void (*reset)(void *ptr);
    int32_t (*get_count)(void *ptr);
    void (*deinit)(void *ptr);
} Greeter_Vtable;

typedef struct Greeter {
    void                *ptr;
    const Greeter_Vtable *vtable;
} Greeter;

static inline char *Greeter_greet(Greeter _self, char *name) {
    return _self.vtable->greet(_self.ptr, name);
}

static inline void Greeter_reset(Greeter _self) {
    _self.vtable->reset(_self.ptr);
}

static inline int32_t Greeter_get_count(Greeter _self) {
    return _self.vtable->get_count(_self.ptr);
}

static inline void Greeter_deinit(Greeter _self) {
    _self.vtable->deinit(_self.ptr);
}

Greeter Greeter_zig_new(void *ptr);

#endif /* TYPES_H */
