/* Generated by zidl from types.idl — DO NOT EDIT */

#include "types.h"
#include "zidl_cdr.h"
#include <stdlib.h>
#include <string.h>

int Point_serialize(ZidlCdrWriter *_w, const Point *_v) {
    int _rc;
    _rc = zidl_cdr_write_i32(_w, _v->x);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_i32(_w, _v->y);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Point_deserialize(ZidlCdrReader *_r, Point *_v) {
    int _rc;
    _rc = zidl_cdr_read_i32(_r, &_v->x);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_i32(_r, &_v->y);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Point_skip(ZidlCdrReader *_r) {
    int _rc;
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

int Sample_serialize(ZidlCdrWriter *_w, const Sample *_v) {
    int _rc;
    _rc = zidl_cdr_write_u32(_w, _v->id);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_bool(_w, _v->b);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u8(_w, _v->u8_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_i16(_w, _v->s16_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u16(_w, _v->u16_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_i32(_w, _v->s32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->u32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_i64(_w, _v->s64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u64(_w, _v->u64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_f32(_w, _v->f32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_f64(_w, _v->f64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_string(_w, _v->str ? _v->str : "", _v->str ? (uint32_t)strlen(_v->str) : 0u);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_string(_w, _v->bstr, (uint32_t)strlen(_v->bstr));
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->nums._length);
    if (_rc) return _rc;
    { uint32_t _si; for (_si = 0; _si < _v->nums._length; _si++) {
        _rc = zidl_cdr_write_i32(_w, _v->nums._buffer[_si]);
        if (_rc) return _rc;
    }
    }
    { uint32_t _ai0; for (_ai0 = 0; _ai0 < 3u; _ai0++) {
        _rc = zidl_cdr_write_i32(_w, _v->arr[_ai0]);
        if (_rc) return _rc;
    }
    }
    _rc = zidl_cdr_write_u32(_w, (uint32_t)_v->clr);
    if (_rc) return _rc;
    _rc = Point_serialize(_w, &_v->nested);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Sample_deserialize(ZidlCdrReader *_r, Sample *_v) {
    int _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->id);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_bool(_r, &_v->b);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u8(_r, &_v->u8_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_i16(_r, &_v->s16_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u16(_r, &_v->u16_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_i32(_r, &_v->s32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->u32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_i64(_r, &_v->s64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u64(_r, &_v->u64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_f32(_r, &_v->f32_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_f64(_r, &_v->f64_val);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_string(_r, &_v->str);
    if (_rc) return _rc;
    { const char *_sp; uint32_t _sl;
        _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl);
        if (_rc) return _rc;
        if (_sl > 32u) return ZIDL_CDR_INVALID;
        memcpy(_v->bstr, _sp, _sl);
        _v->bstr[_sl] = '\0';
    }
    { uint32_t _sl;
        _rc = zidl_cdr_read_u32(_r, &_sl);
        if (_rc) return _rc;
        _v->nums._length = _sl;
        _v->nums._maximum = _sl;
        _v->nums._release = true;
        _v->nums._buffer = (int32_t *)malloc(_sl * sizeof(int32_t));
        if (!_v->nums._buffer && _sl > 0) return ZIDL_CDR_OVERFLOW;
        { uint32_t _si; for (_si = 0; _si < _sl; _si++) {
            _rc = zidl_cdr_read_i32(_r, &_v->nums._buffer[_si]);
            if (_rc) return _rc;
        }
        }
    }
    { uint32_t _ai0; for (_ai0 = 0; _ai0 < 3u; _ai0++) {
        _rc = zidl_cdr_read_i32(_r, &_v->arr[_ai0]);
        if (_rc) return _rc;
    }
    }
    { uint32_t _ev; _rc = zidl_cdr_read_u32(_r, &_ev); if (_rc) return _rc; _v->clr = _ev; }
    _rc = Point_deserialize(_r, &_v->nested);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Sample_skip(ZidlCdrReader *_r) {
    int _rc;
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { bool _tmp; _rc = zidl_cdr_read_bool(_r, &_tmp); if (_rc) return _rc; }
    { uint8_t _tmp; _rc = zidl_cdr_read_u8(_r, &_tmp); if (_rc) return _rc; }
    { int16_t _tmp; _rc = zidl_cdr_read_i16(_r, &_tmp); if (_rc) return _rc; }
    { uint16_t _tmp; _rc = zidl_cdr_read_u16(_r, &_tmp); if (_rc) return _rc; }
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { int64_t _tmp; _rc = zidl_cdr_read_i64(_r, &_tmp); if (_rc) return _rc; }
    { uint64_t _tmp; _rc = zidl_cdr_read_u64(_r, &_tmp); if (_rc) return _rc; }
    { float _tmp; _rc = zidl_cdr_read_f32(_r, &_tmp); if (_rc) return _rc; }
    { double _tmp; _rc = zidl_cdr_read_f64(_r, &_tmp); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    { uint32_t _sl;
        _rc = zidl_cdr_read_u32(_r, &_sl);
        if (_rc) return _rc;
        for (uint32_t _si = 0; _si < _sl; _si++) {
            { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
        }
    }
    { uint32_t _ski0; for (_ski0 = 0; _ski0 < 3u; _ski0++) {
        { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    }
    }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    _rc = Point_skip(_r);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Sample_serialize_key(ZidlCdrWriter *_w, const Sample *_v) {
    int _rc;
    _rc = zidl_cdr_write_u32(_w, _v->id);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Sample_deserialize_key(ZidlCdrReader *_r, Sample *_v) {
    int _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->id);
    if (_rc) return _rc;
    { bool _tmp; _rc = zidl_cdr_read_bool(_r, &_tmp); if (_rc) return _rc; }
    { uint8_t _tmp; _rc = zidl_cdr_read_u8(_r, &_tmp); if (_rc) return _rc; }
    { int16_t _tmp; _rc = zidl_cdr_read_i16(_r, &_tmp); if (_rc) return _rc; }
    { uint16_t _tmp; _rc = zidl_cdr_read_u16(_r, &_tmp); if (_rc) return _rc; }
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { int64_t _tmp; _rc = zidl_cdr_read_i64(_r, &_tmp); if (_rc) return _rc; }
    { uint64_t _tmp; _rc = zidl_cdr_read_u64(_r, &_tmp); if (_rc) return _rc; }
    { float _tmp; _rc = zidl_cdr_read_f32(_r, &_tmp); if (_rc) return _rc; }
    { double _tmp; _rc = zidl_cdr_read_f64(_r, &_tmp); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    { uint32_t _sl;
        _rc = zidl_cdr_read_u32(_r, &_sl);
        if (_rc) return _rc;
        for (uint32_t _si = 0; _si < _sl; _si++) {
            { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
        }
    }
    { uint32_t _ski0; for (_ski0 = 0; _ski0 < 3u; _ski0++) {
        { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    }
    }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    _rc = Point_skip(_r);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Sample_compute_key_hash(const Sample *_v, uint8_t _hash[16]) {
    ZidlCdrWriter _w;
    int _rc = zidl_cdr_writer_init(&_w, ZIDL_XCDR2);
    if (_rc) return _rc;
    zidl_cdr_writer_set_byte_order(&_w, ZIDL_CDR_BE);
    _rc = Sample_serialize_key(&_w, _v);
    if (!_rc) zidl_cdr_compute_key_hash(_w.buf, _w.len, _hash);
    zidl_cdr_writer_deinit(&_w);
    return _rc;
}

int Frame_serialize(ZidlCdrWriter *_w, const Frame *_v) {
    int _rc;
    size_t _dh;
    _rc = zidl_cdr_reserve_dheader_maybe(_w, &_dh);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->seq_num);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_string(_w, _v->topic ? _v->topic : "", _v->topic ? (uint32_t)strlen(_v->topic) : 0u);
    if (_rc) return _rc;
    zidl_cdr_patch_dheader_maybe(_w, _dh);
    return ZIDL_CDR_OK;
}

int Frame_deserialize(ZidlCdrReader *_r, Frame *_v) {
    int _rc;
    _rc = zidl_cdr_skip_dheader_if_xcdr2(_r);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->seq_num);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_string(_r, &_v->topic);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Frame_skip(ZidlCdrReader *_r) {
    int _rc;
    if (_r->xcdr_version == ZIDL_XCDR2) {
        uint32_t _size;
        _rc = zidl_cdr_read_dheader(_r, &_size);
        if (_rc) return _rc;
        return zidl_cdr_skip(_r, _size);
    }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

