/* Hand-written native implementation of io.zzdds.runtime.ZzddsRuntime — see
 * that class's javadoc for the contract. Not generated by zidl: zidl only
 * generates the typed <Topic>TypeSupport/DataWriter/DataReader wrappers that
 * call into this fixed surface (see --generate-zzdds-wrappers's Java
 * backend). Compiled into libzzdds_jni.so alongside the generated entity
 * JNI bridge (dcps_jni.c) — see build.zig's -Djava-binding=true section.
 */
#include <jni.h>
#include <pthread.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "dcps.h"
#include "zzdds_c.h"

/* Defined (non-static, on purpose) in the generated dcps_jni.c, compiled
 * into the same libzzdds_jni.so -- see that function's own doc comment.
 * GuardCondition has no factory operation in dcps.idl (app-instantiated
 * directly per spec), so createGuardCondition() below constructs its Java
 * object by hand rather than through the generated zidl_java_box_DDS_
 * GuardCondition, and needs to register it into Condition's shared
 * box-identity cache itself -- otherwise WaitSet.wait()'s generic
 * zidl_java_box_DDS_Condition would still construct an unrelated second
 * object for the same handle, even with the shared cache in place on the
 * generated side. See zzdds's docs/roadmap.md and zidl's docs/roadmap.md
 * "Binding design review: decision" for the fuller writeup. */
extern void _zidl_family_DDS_Condition_register_external(JNIEnv *env, void *handle, jobject obj);

static void *zzdds_java_unbox(JNIEnv *env, jobject obj) {
    if (obj == NULL) return NULL;
    jclass cls = (*env)->GetObjectClass(env, obj);
    jfieldID fid = (*env)->GetFieldID(env, cls, "ptr_", "J");
    return (void *)(intptr_t)(*env)->GetLongField(env, obj, fid);
}

/* ── Lazily-cached (jclass, "(J)V" ctor jmethodID) pairs ─────────────────
 *
 * createFactory()/asZzddsDataWriter() each resolve their target class once
 * and cache it in a `static` local for subsequent calls. Without
 * synchronization, two threads racing on the *first* call can interleave:
 * one observes the other's non-NULL `cls` (a plain store, visible as soon
 * as it happens to land in this thread's view of memory — nothing enforces
 * an ordering) before that thread has finished writing `ctor`, and calls
 * NewObject with a NULL/stale method ID — a JNI fatal error or crash. One
 * shared mutex serializes both the first-time init and every subsequent
 * read of the pair, so a fully-initialized cache is always observed as a
 * whole. */
typedef struct {
    jclass cls;
    jmethodID ctor;
} zzdds_java_class_cache;

static pthread_mutex_t zzdds_java_class_cache_mu = PTHREAD_MUTEX_INITIALIZER;

/* Resolves `class_name`'s (jclass, "(J)V" constructor) pair into `*cache`,
 * caching it globally after the first successful call. Returns false
 * (leaving `*cache` untouched, so a later call retries from scratch) if
 * FindClass, NewGlobalRef, or GetMethodID fails — a Java exception is left
 * pending in each case; callers return NULL and let it propagate rather
 * than passing a null jclass/jmethodID into NewObject. Safe to call
 * concurrently from multiple threads. */
static bool zzdds_java_get_or_cache_class(JNIEnv *env, zzdds_java_class_cache *cache, const char *class_name) {
    pthread_mutex_lock(&zzdds_java_class_cache_mu);
    if (cache->cls == NULL) {
        jclass local = (*env)->FindClass(env, class_name);
        if (local == NULL) {
            pthread_mutex_unlock(&zzdds_java_class_cache_mu);
            return false;
        }
        jclass global = (jclass)(*env)->NewGlobalRef(env, local);
        (*env)->DeleteLocalRef(env, local);
        if (global == NULL) {
            pthread_mutex_unlock(&zzdds_java_class_cache_mu);
            return false;
        }
        jmethodID ctor = (*env)->GetMethodID(env, global, "<init>", "(J)V");
        if (ctor == NULL) {
            (*env)->DeleteGlobalRef(env, global);
            pthread_mutex_unlock(&zzdds_java_class_cache_mu);
            return false;
        }
        cache->ctor = ctor;
        cache->cls = global;
    }
    pthread_mutex_unlock(&zzdds_java_class_cache_mu);
    return true;
}

/* ── Factory bootstrap ──────────────────────────────────────────────────
 *
 * There is no IDL-level "get the singleton DomainParticipantFactory"
 * operation (see zzdds/docs/language-bindings.md) — every zzdds binding
 * bootstraps through this same hand-written zzdds_create_factory() call
 * (C/C++ examples do the same thing via zzdds_c.h directly).
 */
JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_createFactory(JNIEnv *env, jclass self_cls) {
    (void)self_cls;
    zzdds_DomainParticipantFactory zf = zzdds_create_factory();
    if (zzdds_factory_is_nil(zf)) return NULL;
    DDS_DomainParticipantFactory df = zzdds_DomainParticipantFactory_as_DDS_DomainParticipantFactory(zf);

    static zzdds_java_class_cache cache = {0};
    if (!zzdds_java_get_or_cache_class(env, &cache, "io/zzdds/dcps/DomainParticipantFactoryImpl")) return NULL;
    return (*env)->NewObject(env, cache.cls, cache.ctor, (jlong)(intptr_t)df);
}

/* ── WaitSet / GuardCondition bootstrap ──────────────────────────────────
 *
 * Same reasoning as createFactory() above: neither has a factory operation
 * in dcps.idl (per OMG spec, both are app-instantiated directly), so both
 * bootstrap through the same hand-written zzdds_create_waitset()/
 * zzdds_create_guardcondition() the C/C++ examples use. Unlike
 * DomainParticipantFactory, neither is a zzdds-extended type, so the boxed
 * handle these return is already the right DDS_WaitSet/DDS_GuardCondition
 * shape -- no _as_DDS_ upcast step needed before boxing into the generated
 * WaitSetImpl/GuardConditionImpl Java class.
 */
/* ── WaitSet condition-attachment keepalive ──────────────────────────────
 *
 * Mirrors zzdds_cpp.hpp's WaitSetSupport::attach_condition -- see that
 * class's own doc comment for the full "why" (WaitSet attachment is not
 * ownership per spec, but a caller who drops their only Java reference to
 * an attached condition right after attaching would otherwise be left
 * holding a dangling wrapper the moment the underlying C-ABI entity is torn
 * down). Java has no equivalent of C++'s virtual-dispatch override (there is
 * no --java-impl-override, and WaitSetImpl.java is plain generated code) --
 * so instead of a subclass, this hooks in via JNI's RegisterNatives,
 * overriding WaitSetImpl's own generated n_attach_condition native binding
 * with the implementation below. Completely transparent to callers:
 * WaitSetImpl.java's public attach_condition()/detach_condition() methods
 * are unchanged, only which native implementation backs the private
 * n_attach_condition dispatch point changes. detach_condition needs no
 * override: the plain, inherited n_detach_condition already fires the same
 * release_fn, since it's the same underlying C-ABI attachment record either
 * way -- see zzdds_waitset_attach_condition_with_release's own doc comment
 * in zzdds_c.h.
 *
 * An earlier revision of this section pre-checked "is this condition
 * already attached" against a JNI-side list of its own before deciding
 * whether to register a release hook, and (once that check itself was made
 * atomic) also tried overriding n_detach_condition to keep that list in
 * sync. Both were the wrong tool: no ordering of a caller-side cache check
 * against a concurrent attach/detach on another thread can ever be made
 * airtight, because the cache and the real Zig-side attachment state are
 * protected by two different locks that are never held together (Greptile's
 * PR #62 review re-discovered a new variant of this three times running).
 * Fixed at the root instead: zzdds_waitset_attach_condition_with_release's
 * out_accepted parameter now reports, atomically under the Zig side's own
 * internal lock, whether THIS call's own release_ctx actually got stored
 * (true) or discarded as a duplicate (false) -- always attempt the real
 * registration and trust that answer, never guess first. And each
 * registration's ctx now owns its own JNI global ref directly (no shared
 * list at all), so release_trampoline never needs to look anything up by a
 * (waitset, handle) key that a concurrent reattach could have already
 * reused for a brand new, unrelated registration.
 */

/* zidl's generated dcps_jni.c (compiled into this same libzzdds_jni.so)
 * already captures the JavaVM* in JNI_OnLoad -- see this file's own later
 * zzdds_java_get_env() wrapper (TypeSupport section, below) for the fuller
 * comment on why this is declared here rather than defined twice. Declared
 * directly (not via that wrapper) because it's needed before that section
 * of the file is reached. */
extern JNIEnv *zidl_java_get_env(void);

typedef struct {
    /* Always a real, non-NULL global ref by the time a ctx reaches either
     * this trampoline or attach_condition's own cleanup path below --
     * zzdds_java_waitset_attach_condition never lets a ctx with a failed
     * NewGlobalRef proceed any further (see its own doc comment). */
    jobject global_ref;
} zzdds_java_waitset_release_ctx;

/* Fires from inside zzdds, outside any zzdds-internal lock, on whichever of
 * the three ways an attachment ends -- never synchronously from within
 * zzdds_java_waitset_attach_condition itself for an ACCEPTED registration
 * (only detach/destroy paths fire it for those); it CAN fire synchronously,
 * inline, when the registration attempt was a discarded duplicate -- see
 * zzdds_java_waitset_attach_condition's own handling of that case, which
 * frees ctx directly instead of going through this trampoline at all, so
 * this function only ever runs for a genuinely accepted registration. */
static void zzdds_java_waitset_release_trampoline(void *ctx_raw) {
    zzdds_java_waitset_release_ctx *ctx = (zzdds_java_waitset_release_ctx *)ctx_raw;
    JNIEnv *env = zidl_java_get_env();
    if (env != NULL) (*env)->DeleteGlobalRef(env, ctx->global_ref);
    free(ctx);
}

/* Resolves `cond`'s raw DDS_Condition handle regardless of its concrete
 * Java class -- mirrors zzdds_cpp.hpp's WaitSetSupport::resolve_handle
 * (an IsInstanceOf cascade here instead of dynamic_cast, same shape as
 * zidl's own generated zidl_java_unbox_as_DDS_Condition dispatcher in
 * dcps_jni.c, which this doesn't reuse only because that one is file-local
 * `static`, not because the logic needs to differ). */
static void *zzdds_java_resolve_condition_handle(JNIEnv *env, jobject cond) {
    void *raw = zzdds_java_unbox(env, cond);
    static zzdds_java_class_cache guard_cache = {0}, status_cache = {0}, read_cache = {0}, query_cache = {0};
    if (zzdds_java_get_or_cache_class(env, &guard_cache, "io/zzdds/dcps/GuardConditionImpl") &&
        (*env)->IsInstanceOf(env, cond, guard_cache.cls)) {
        return (void *)DDS_GuardCondition_as_DDS_Condition(raw);
    }
    if (zzdds_java_get_or_cache_class(env, &status_cache, "io/zzdds/dcps/StatusConditionImpl") &&
        (*env)->IsInstanceOf(env, cond, status_cache.cls)) {
        return (void *)DDS_StatusCondition_as_DDS_Condition(raw);
    }
    if (zzdds_java_get_or_cache_class(env, &query_cache, "io/zzdds/dcps/QueryConditionImpl") &&
        (*env)->IsInstanceOf(env, cond, query_cache.cls)) {
        return (void *)DDS_ReadCondition_as_DDS_Condition(DDS_QueryCondition_as_DDS_ReadCondition(raw));
    }
    if (zzdds_java_get_or_cache_class(env, &read_cache, "io/zzdds/dcps/ReadConditionImpl") &&
        (*env)->IsInstanceOf(env, cond, read_cache.cls)) {
        return (void *)DDS_ReadCondition_as_DDS_Condition(raw);
    }
    return raw; /* plain DDS_Condition (or an already-Condition-typed handle) */
}

/* Deliberately does NOT pre-check "is this condition already attached"
 * against any bookkeeping of its own before deciding whether to register a
 * release hook -- see this section's own top-of-file doc comment for why
 * that approach (tried, and iterated on, across three rounds of PR #62
 * review) was fundamentally the wrong tool. Always attempts the real
 * with-release registration and trusts out_accepted, computed atomically by
 * the Zig side itself. */
static jint JNICALL zzdds_java_waitset_attach_condition(JNIEnv *env, jobject self, jlong ptr, jobject cond) {
    (void)self;
    void *waitset = (void *)(intptr_t)ptr;
    if (cond == NULL) return (jint)DDS_WaitSet_attach_condition(waitset, NULL);
    void *h = zzdds_java_resolve_condition_handle(env, cond);

    /* Both allocation steps below must fully succeed before this attaches
     * anything -- an earlier revision fell back to a plain, hookless attach
     * (still returning DDS_RETCODE_OK) when either failed, on the theory
     * that "best effort, OOM just means no keepalive" was an acceptable
     * degradation. It isn't: that path let attach_condition() report
     * success while silently skipping the exact lifetime protection this
     * whole mechanism exists to provide, right when memory pressure makes
     * losing that protection most likely to actually matter (Greptile PR
     * #62 P1: "OOM creates hookless attachment"). Reporting the real,
     * standard DDS_RETCODE_OUT_OF_RESOURCES instead — mirroring how
     * attachConditionWithRelease's own WAKEUP_SLOTS-full case already
     * refuses to silently succeed — means an attach that returns OK is now
     * unconditionally a fully-protected one; a caller that ignores this
     * particular non-OK return code is no worse off than one that ignores
     * any other DDS_ReturnCode_t. */
    zzdds_java_waitset_release_ctx *ctx = malloc(sizeof(zzdds_java_waitset_release_ctx));
    if (ctx == NULL) return (jint)DDS_RETCODE_OUT_OF_RESOURCES;
    ctx->global_ref = (*env)->NewGlobalRef(env, cond);
    if (ctx->global_ref == NULL) {
        free(ctx);
        return (jint)DDS_RETCODE_OUT_OF_RESOURCES;
    }

    bool accepted = false;
    jint rc = (jint)zzdds_waitset_attach_condition_with_release(waitset, h, ctx, zzdds_java_waitset_release_trampoline, &accepted);
    if (rc != DDS_RETCODE_OK || !accepted) {
        /* Either the attach itself failed (ctx was never stored), or it
         * succeeded but as a no-op duplicate of an existing attachment
         * (ctx was still never stored -- the existing attachment's own
         * release_ctx/release_fn is untouched, exactly as documented).
         * Either way, release_trampoline will never run for this ctx; it's
         * safe -- and necessary -- to clean it up directly here. */
        (*env)->DeleteGlobalRef(env, ctx->global_ref);
        free(ctx);
    }
    return rc;
}

static pthread_once_t zzdds_java_waitset_natives_once = PTHREAD_ONCE_INIT;

/* Deliberately does NOT take a JNIEnv from its caller -- an earlier version
 * stashed the calling thread's env in a plain (unsynchronized) global
 * before calling pthread_once, but pthread_once only guarantees the
 * *callback* runs exactly once, not that it's the SAME thread that stashed
 * the winning value: if two threads both reach createWaitSet for the first
 * time concurrently, each writes its own env to that global before either
 * calls pthread_once, so whichever thread's once callback actually runs
 * could easily end up reading the OTHER thread's JNIEnv -- a JNIEnv is only
 * valid on the thread that owns it, so using one from a different thread is
 * undefined behavior (can crash or corrupt the JVM). Fixed (Greptile PR #62
 * P1: "shared JNI environment crosses threads") by having the once callback
 * fetch a JNIEnv valid for whichever thread actually ends up running it,
 * via zidl_java_get_env() (JNI's JavaVM* is itself thread-safe to call from
 * any thread), instead of trusting a value some other thread may have
 * written. */
static void zzdds_java_waitset_natives_once_fn(void) {
    JNIEnv *env = zidl_java_get_env();
    if (env == NULL) return;
    jclass cls = (*env)->FindClass(env, "io/zzdds/dcps/WaitSetImpl");
    if (cls == NULL) { (*env)->ExceptionClear(env); return; }
    JNINativeMethod methods[] = {
        { (char *)"n_attach_condition", (char *)"(JLio/zzdds/dcps/Dcps$DDS$Condition;)I",
          (void *)zzdds_java_waitset_attach_condition },
    };
    (*env)->RegisterNatives(env, cls, methods, 1);
    (*env)->DeleteLocalRef(env, cls);
}

/* Called from createWaitSet below, which always runs before any app could
 * possibly have a WaitSet to attach a condition to -- pthread_once
 * guarantees the actual registration happens exactly once regardless of how
 * many threads call createWaitSet concurrently. */
static void zzdds_java_ensure_waitset_natives_registered(void) {
    pthread_once(&zzdds_java_waitset_natives_once, zzdds_java_waitset_natives_once_fn);
}

JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_createWaitSet(JNIEnv *env, jclass self_cls) {
    (void)self_cls;
    zzdds_java_ensure_waitset_natives_registered();
    DDS_WaitSet ws = zzdds_create_waitset();
    if (zzdds_waitset_is_nil(ws)) return NULL;
    static zzdds_java_class_cache cache = {0};
    if (!zzdds_java_get_or_cache_class(env, &cache, "io/zzdds/dcps/WaitSetImpl")) return NULL;
    return (*env)->NewObject(env, cache.cls, cache.ctor, (jlong)(intptr_t)ws);
}

JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_createGuardCondition(JNIEnv *env, jclass self_cls) {
    (void)self_cls;
    DDS_GuardCondition gc = zzdds_create_guardcondition();
    if (zzdds_guardcondition_is_nil(gc)) return NULL;
    static zzdds_java_class_cache cache = {0};
    if (!zzdds_java_get_or_cache_class(env, &cache, "io/zzdds/dcps/GuardConditionImpl")) return NULL;
    jobject obj = (*env)->NewObject(env, cache.cls, cache.ctor, (jlong)(intptr_t)gc);
    if (obj == NULL) return NULL;
    _zidl_family_DDS_Condition_register_external(env, (void *)DDS_GuardCondition_as_DDS_Condition(gc), obj);
    return obj;
}

/* WaitSet/GuardCondition have no owning factory to delete them through --
 * mirrors zzdds_destroy_factory's role, just with no Java-callable
 * equivalent to reach for otherwise (unlike DomainParticipant, entity
 * interfaces have no deinit() exposed as a Java method at all -- see
 * Dcps.DDS.WaitSet/GuardCondition's generated interface). */
JNIEXPORT void JNICALL Java_io_zzdds_runtime_ZzddsRuntime_destroyWaitSet(JNIEnv *env, jclass self_cls, jobject waitset) {
    (void)self_cls;
    DDS_WaitSet ws = (DDS_WaitSet)zzdds_java_unbox(env, waitset);
    if (ws == NULL) return;
    zzdds_destroy_waitset(ws);
}

JNIEXPORT void JNICALL Java_io_zzdds_runtime_ZzddsRuntime_destroyGuardCondition(JNIEnv *env, jclass self_cls, jobject guardcondition) {
    (void)self_cls;
    DDS_GuardCondition gc = (DDS_GuardCondition)zzdds_java_unbox(env, guardcondition);
    if (gc == NULL) return;
    zzdds_destroy_guardcondition(gc);
}

/* ── TypeSupport registration: one native trampoline, ctx-carrying ──────
 *
 * zzdds_register_type_support_ctx (see zzdds_c.h) forwards an opaque ctx
 * to every compute_key_hash call, so — unlike the plain, no-ctx
 * zzdds_register_type_support that C/C++/Zig use — one shared trampoline
 * here can dispatch to whichever Java Class<?>/jmethodID a given
 * registration was for, with no fixed slot table and no per-registration
 * lock: each registration gets its own independent heap allocation, freed
 * by zzdds core (via ctx_deinit) exactly when that registration is replaced
 * or its participant is destroyed — see registerTypeSupport/deinit in
 * zzdds/src/dcps/participant.zig, which already reclaims TypeSupport ctx
 * this way for the non-Java C ABI path too.
 */
/* zidl's generated dcps_jni.c (compiled into this same libzzdds_jni.so)
 * already defines JNI_OnLoad and captures the JavaVM* into its own
 * zidl_java_vm exactly once, before any native method in this library can
 * be called from Java — a second JNI_OnLoad here would be a duplicate
 * symbol at link time, and a lazily-captured JavaVM* of our own (e.g. on
 * first registerTypeSupport call) would leave a real race: a transport
 * thread's key-hash dispatch could observe it still NULL if it raced the
 * very first registration. Reuse zidl's already-correct capture instead of
 * duplicating the mechanism. */
extern JNIEnv *zidl_java_get_env(void);

static JNIEnv *zzdds_java_get_env(void) {
    return zidl_java_get_env();
}

typedef struct {
    jclass cls;    /* global ref */
    jmethodID mid;
    /* Optional: resolved from the type's own generated `getFieldFromCdr`
     * static method (see java.zig's `Generator.emitGetFieldFromCdr`). NULL
     * if the class has no such method (e.g. a hand-written TypeSupport
     * class predating this contract) -- CFT auto-filtering just doesn't
     * activate for that type, same as any other binding's TypeSupport with
     * a NULL get_field_fn. */
    jmethodID get_field_mid;
} zzdds_java_ts_ctx;

static int zzdds_java_compute_key_hash_ctx(void *ctx_v, const uint8_t *payload, size_t len, uint8_t hash_out[16]) {
    zzdds_java_ts_ctx *ctx = (zzdds_java_ts_ctx *)ctx_v;
    JNIEnv *env = zzdds_java_get_env();
    if (env == NULL) return -1;
    jbyteArray arr = (*env)->NewByteArray(env, (jsize)len);
    (*env)->SetByteArrayRegion(env, arr, 0, (jsize)len, (const jbyte *)payload);
    jbyteArray hash = (jbyteArray)(*env)->CallStaticObjectMethod(env, ctx->cls, ctx->mid, arr);
    if (hash == NULL) return -1;
    (*env)->GetByteArrayRegion(env, hash, 0, 16, (jbyte *)hash_out);
    return 0;
}

/* Trampoline for zzdds_get_field_from_cdr_ctx_fn (zzdds_c.h) -- calls the
 * type's generated `static Object getFieldFromCdr(byte[] payload, String
 * field)` (see java.zig's `Generator.emitGetFieldFromCdr`) and converts its
 * boxed Long/Double/String result into `*out`. Unlike the C/C++ backends'
 * generated get_field_from_cdr, there is no dangling-pointer hazard to
 * design `scratch` around on the Java side -- the JVM's GC keeps a returned
 * String's backing memory alive on its own -- but the wire contract (a
 * caller-supplied `scratch` buffer for the matched string's bytes) is fixed
 * by zzdds_c.h for every ctx-carrying binding alike, so this still copies
 * into it rather than inventing a Java-only shortcut.
 */
static bool zzdds_java_get_field_from_cdr_ctx(
    void *ctx_v,
    const uint8_t *payload, size_t payload_len,
    const char *field, size_t field_len,
    zzdds_filter_value *out,
    uint8_t *scratch, size_t scratch_len)
{
    zzdds_java_ts_ctx *ctx = (zzdds_java_ts_ctx *)ctx_v;
    if (ctx->get_field_mid == NULL) return false;
    JNIEnv *env = zzdds_java_get_env();
    if (env == NULL) return false;

    jbyteArray arr = (*env)->NewByteArray(env, (jsize)payload_len);
    (*env)->SetByteArrayRegion(env, arr, 0, (jsize)payload_len, (const jbyte *)payload);

    /* `field`/`field_len` is a non-null-terminated byte range (matches every
     * other binding's get_field_from_cdr contract) -- NewStringUTF needs a
     * null-terminated one. Field names are short IDL identifiers; a filter
     * expression referencing one longer than this never matches any real
     * member anyway, so treating it as "no match" here is harmless. */
    char namebuf[128];
    if (field_len >= sizeof(namebuf)) return false;
    memcpy(namebuf, field, field_len);
    namebuf[field_len] = '\0';
    jstring jfield = (*env)->NewStringUTF(env, namebuf);

    jobject result = (*env)->CallStaticObjectMethod(env, ctx->cls, ctx->get_field_mid, arr, jfield);
    if ((*env)->ExceptionCheck(env)) {
        (*env)->ExceptionClear(env);
        return false;
    }
    if (result == NULL) return false;

    /* Benign race across concurrent first calls (see emitBoxHelper's own
     * doc comment on this exact pattern): FindClass/GetMethodID are
     * idempotent, so a redundant lookup is harmless. */
    static jclass long_cls = NULL, double_cls = NULL, string_cls = NULL;
    static jmethodID long_value_mid = NULL, double_value_mid = NULL;
    if (long_cls == NULL) {
        jclass local = (*env)->FindClass(env, "java/lang/Long");
        long_cls = (jclass)(*env)->NewGlobalRef(env, local);
        long_value_mid = (*env)->GetMethodID(env, long_cls, "longValue", "()J");
    }
    if (double_cls == NULL) {
        jclass local = (*env)->FindClass(env, "java/lang/Double");
        double_cls = (jclass)(*env)->NewGlobalRef(env, local);
        double_value_mid = (*env)->GetMethodID(env, double_cls, "doubleValue", "()D");
    }
    if (string_cls == NULL) {
        jclass local = (*env)->FindClass(env, "java/lang/String");
        string_cls = (jclass)(*env)->NewGlobalRef(env, local);
    }

    if ((*env)->IsInstanceOf(env, result, long_cls)) {
        out->kind = 0;
        out->i = (int64_t)(*env)->CallLongMethod(env, result, long_value_mid);
        return true;
    }
    if ((*env)->IsInstanceOf(env, result, double_cls)) {
        out->kind = 1;
        out->f = (*env)->CallDoubleMethod(env, result, double_value_mid);
        return true;
    }
    if ((*env)->IsInstanceOf(env, result, string_cls)) {
        const char *cs = (*env)->GetStringUTFChars(env, (jstring)result, NULL);
        size_t len = strlen(cs);
        if (len > scratch_len) {
            (*env)->ReleaseStringUTFChars(env, (jstring)result, cs);
            return false;
        }
        memcpy(scratch, cs, len);
        (*env)->ReleaseStringUTFChars(env, (jstring)result, cs);
        out->kind = 2;
        out->s_ptr = scratch;
        out->s_len = len;
        return true;
    }
    return false;
}

/* Called by zzdds core exactly once, when this registration is replaced or
 * its participant is destroyed (see the block comment above). */
static void zzdds_java_ts_ctx_deinit(void *ctx_v) {
    zzdds_java_ts_ctx *ctx = (zzdds_java_ts_ctx *)ctx_v;
    JNIEnv *env = zzdds_java_get_env();
    if (env != NULL) (*env)->DeleteGlobalRef(env, ctx->cls);
    free(ctx);
}

JNIEXPORT jint JNICALL Java_io_zzdds_runtime_ZzddsRuntime_registerTypeSupport(
    JNIEnv *env, jclass self_cls, jobject participant, jstring typeName, jclass typeClass)
{
    (void)self_cls;

    zzdds_java_ts_ctx *ctx = malloc(sizeof(*ctx));
    if (ctx == NULL) return -1;
    ctx->cls = (jclass)(*env)->NewGlobalRef(env, typeClass);
    if (ctx->cls == NULL) {
        free(ctx);
        return -1;
    }
    ctx->mid = (*env)->GetStaticMethodID(env, typeClass, "computeKeyHashFromCdr", "([B)[B");
    if (ctx->mid == NULL) {
        (*env)->DeleteGlobalRef(env, ctx->cls);
        free(ctx);
        return -1;
    }
    /* Optional (see zzdds_java_ts_ctx's doc comment) -- clear the pending
     * NoSuchMethodError rather than letting it propagate, unlike mid above. */
    ctx->get_field_mid = (*env)->GetStaticMethodID(env, typeClass, "getFieldFromCdr", "([BLjava/lang/String;)Ljava/lang/Object;");
    if (ctx->get_field_mid == NULL) (*env)->ExceptionClear(env);

    void *p = zzdds_java_unbox(env, participant);
    const char *type_name_c = (*env)->GetStringUTFChars(env, typeName, NULL);
    /* Only wire the get_field trampoline in when the class actually has a
     * getFieldFromCdr to call -- passing it unconditionally would still
     * behave correctly (the trampoline itself checks get_field_mid and
     * returns false, which zzdds's filter evaluator treats the same as "no
     * get_field": pass every sample through), but skips a pointless
     * per-field JNI round trip for a class that will never resolve one. */
    zzdds_get_field_from_cdr_ctx_fn get_field_fn = ctx->get_field_mid != NULL ? zzdds_java_get_field_from_cdr_ctx : NULL;
    int rc = zzdds_register_type_support_ctx(p, type_name_c, zzdds_java_compute_key_hash_ctx, get_field_fn, ctx, zzdds_java_ts_ctx_deinit);
    (*env)->ReleaseStringUTFChars(env, typeName, type_name_c);

    if (rc != 0) {
        /* Registration didn't take — nothing installed it, so nothing will
         * ever call ctx_deinit for it; release what we just allocated
         * ourselves instead of leaking it. */
        (*env)->DeleteGlobalRef(env, ctx->cls);
        free(ctx);
    }
    return rc;
}

/* ── Write/dispose/unregister ───────────────────────────────────────────
 * `kind` matches zzdds_write_kind (0=alive, 1=dispose, 2=unregister) — see
 * ZzddsRuntime.writeRaw's javadoc. */
JNIEXPORT jint JNICALL Java_io_zzdds_runtime_ZzddsRuntime_writeRaw(
    JNIEnv *env, jclass self_cls, jobject writer, jint kind, jbyteArray keyHash, jlong handle, jbyteArray payload)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    jsize payload_len = (*env)->GetArrayLength(env, payload);
    jbyte *payload_buf = (*env)->GetByteArrayElements(env, payload, NULL);
    int rc = zzdds_write_raw_kind(
        w, (zzdds_write_kind)kind, (const uint8_t *)hash_buf,
        (DDS_InstanceHandle_t)handle, (const uint8_t *)payload_buf, (size_t)payload_len);
    (*env)->ReleaseByteArrayElements(env, payload, payload_buf, JNI_ABORT);
    return rc;
}

JNIEXPORT jint JNICALL Java_io_zzdds_runtime_ZzddsRuntime_writeRawWTimestamp(
    JNIEnv *env, jclass self_cls, jobject writer, jint kind, jbyteArray keyHash, jlong handle, jbyteArray payload, jint sec, jint nanosec)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    jsize payload_len = (*env)->GetArrayLength(env, payload);
    jbyte *payload_buf = (*env)->GetByteArrayElements(env, payload, NULL);
    DDS_Time_t timestamp = { .sec = (int32_t)sec, .nanosec = (uint32_t)nanosec };
    int rc = zzdds_write_raw_w_timestamp(
        w, (zzdds_write_kind)kind, (const uint8_t *)hash_buf,
        (DDS_InstanceHandle_t)handle, (const uint8_t *)payload_buf, (size_t)payload_len, timestamp);
    (*env)->ReleaseByteArrayElements(env, payload, payload_buf, JNI_ABORT);
    return rc;
}

JNIEXPORT jlong JNICALL Java_io_zzdds_runtime_ZzddsRuntime_registerInstanceRaw(
    JNIEnv *env, jclass self_cls, jobject writer, jbyteArray keyHash)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    return (jlong)zzdds_register_instance_raw(w, (const uint8_t *)hash_buf);
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_getKeyValueWriterRaw(
    JNIEnv *env, jclass self_cls, jobject writer, jlong handle)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    uint8_t buf[4096];
    size_t len = 0;
    if (zzdds_get_key_value_writer(w, (DDS_InstanceHandle_t)handle, buf, sizeof(buf), &len) != 0) return NULL;
    jbyteArray result = (*env)->NewByteArray(env, (jsize)len);
    (*env)->SetByteArrayRegion(env, result, 0, (jsize)len, (const jbyte *)buf);
    return result;
}

JNIEXPORT jlong JNICALL Java_io_zzdds_runtime_ZzddsRuntime_lookupInstanceWriterRaw(
    JNIEnv *env, jclass self_cls, jobject writer, jbyteArray keyHash)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    return (jlong)zzdds_lookup_instance_writer(w, (const uint8_t *)hash_buf);
}

/* ── Take/read ───────────────────────────────────────────────────────── */

static jbyteArray zzdds_java_take_or_read(
    JNIEnv *env, jobject reader_obj, jint max_size, jlongArray handle_out, jbooleanArray valid_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    uint8_t *buf = malloc((size_t)max_size);
    if (buf == NULL) return NULL;

    zzdds_sample_info info;
    size_t cdr_len = 0;
    DDS_ReturnCode_t n = is_take
        ? zzdds_take_one_raw(reader, buf, (size_t)max_size, &cdr_len, &info)
        : zzdds_read_one_raw(reader, buf, (size_t)max_size, &cdr_len, &info);
    if (n != DDS_RETCODE_OK) {
        free(buf);
        return NULL;
    }

    jlong handle_val = (jlong)info.instance_handle;
    jboolean valid_val = info.valid_data ? JNI_TRUE : JNI_FALSE;
    (*env)->SetLongArrayRegion(env, handle_out, 0, 1, &handle_val);
    (*env)->SetBooleanArrayRegion(env, valid_out, 0, 1, &valid_val);

    jbyteArray result = (*env)->NewByteArray(env, (jsize)cdr_len);
    (*env)->SetByteArrayRegion(env, result, 0, (jsize)cdr_len, (const jbyte *)buf);
    free(buf);
    return result;
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read(env, reader, maxSize, handleOut, validOut, 1);
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read(env, reader, maxSize, handleOut, validOut, 0);
}

/* ── Take/read next instance ─────────────────────────────────────────── */

static jbyteArray zzdds_java_take_or_read_instance(
    JNIEnv *env, jobject reader_obj, jlong prev, jint max_size, jlongArray handle_out, jbooleanArray valid_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    uint8_t *buf = malloc((size_t)max_size);
    if (buf == NULL) return NULL;

    zzdds_sample_info info;
    size_t cdr_len = 0;
    DDS_ReturnCode_t n = is_take
        ? zzdds_take_one_raw_instance(reader, (DDS_InstanceHandle_t)prev, buf, (size_t)max_size, &cdr_len, &info)
        : zzdds_read_one_raw_instance(reader, (DDS_InstanceHandle_t)prev, buf, (size_t)max_size, &cdr_len, &info);
    if (n != DDS_RETCODE_OK) {
        free(buf);
        return NULL;
    }

    jlong handle_val = (jlong)info.instance_handle;
    jboolean valid_val = info.valid_data ? JNI_TRUE : JNI_FALSE;
    (*env)->SetLongArrayRegion(env, handle_out, 0, 1, &handle_val);
    (*env)->SetBooleanArrayRegion(env, valid_out, 0, 1, &valid_val);

    jbyteArray result = (*env)->NewByteArray(env, (jsize)cdr_len);
    (*env)->SetByteArrayRegion(env, result, 0, (jsize)cdr_len, (const jbyte *)buf);
    free(buf);
    return result;
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeNextInstanceRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jlong prev, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_instance(env, reader, prev, maxSize, handleOut, validOut, 1);
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readNextInstanceRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jlong prev, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_instance(env, reader, prev, maxSize, handleOut, validOut, 0);
}

/* ── Bulk take/read ───────────────────────────────────────────────────────
 *
 * Unlike takeRaw/readRaw/takeNextInstanceRaw/readNextInstanceRaw, zzdds_take_n_raw/
 * zzdds_read_n_raw allocate each sample's buffer themselves, sized exactly to
 * that sample's real CDR length -- there is no caller-supplied max-per-sample
 * buffer size to plumb through here, unlike the single-sample calls above.
 * `max` (`ss`/`vs`/`is` mask-filtered) IS still caller-bounded, same as C/C++'s
 * own take_n/read_n -- Java's `handlesOut`/`validsOut` are pre-sized to `max`
 * by the caller (see ZzddsRuntime.takeNRaw/readNRaw's javadoc): this function
 * only ever fills the first N <= max entries, where N is the returned
 * byte[][]'s own length (the true count) -- the caller must not treat the
 * rest of handlesOut/validsOut as meaningful.
 */

/* Packages a zzdds_raw_sample_array into a jbyteArray[], filling
 * handles_out/valids_out in parallel, and frees `arr` either way. Shared
 * tail of every bulk take/read JNI function below (take_n/read_n,
 * take_instance/read_instance, take_w_condition/read_w_condition,
 * take_next_instance_w_condition/read_next_instance_w_condition), which
 * otherwise only differ in which zzdds_*_raw call produces `arr`. `n <= 0`
 * (already checked by the caller) means `arr` was never populated -- callers
 * must not reach here in that case. */
static jobjectArray zzdds_java_package_arr(
    JNIEnv *env, void *reader, zzdds_raw_sample_array *arr,
    jlongArray handles_out, jbooleanArray valids_out)
{
    jclass byte_array_cls = (*env)->FindClass(env, "[B");
    if (byte_array_cls == NULL) {
        zzdds_return_raw_samples(reader, arr);
        return NULL;
    }
    jobjectArray result = (*env)->NewObjectArray(env, (jsize)arr->count, byte_array_cls, NULL);
    for (size_t i = 0; i < arr->count; i++) {
        zzdds_raw_sample *s = &arr->samples[i];
        jbyteArray payload = (*env)->NewByteArray(env, (jsize)s->data_len);
        (*env)->SetByteArrayRegion(env, payload, 0, (jsize)s->data_len, (const jbyte *)s->data);
        (*env)->SetObjectArrayElement(env, result, (jsize)i, payload);
        (*env)->DeleteLocalRef(env, payload);

        jlong handle_val = (jlong)s->info.instance_handle;
        jboolean valid_val = s->info.valid_data ? JNI_TRUE : JNI_FALSE;
        (*env)->SetLongArrayRegion(env, handles_out, (jsize)i, 1, &handle_val);
        (*env)->SetBooleanArrayRegion(env, valids_out, (jsize)i, 1, &valid_val);
    }
    zzdds_return_raw_samples(reader, arr);
    return result;
}

static jobjectArray zzdds_java_take_or_read_n(
    JNIEnv *env, jobject reader_obj, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handles_out, jbooleanArray valids_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    zzdds_raw_sample_array arr;
    int n = is_take
        ? zzdds_take_n_raw(reader, (uint32_t)ss, (uint32_t)vs, (uint32_t)is_mask, (int)max, &arr)
        : zzdds_read_n_raw(reader, (uint32_t)ss, (uint32_t)vs, (uint32_t)is_mask, (int)max, &arr);
    if (n <= 0) {
        jclass byte_array_cls = (*env)->FindClass(env, "[B");
        return byte_array_cls == NULL ? NULL : (*env)->NewObjectArray(env, 0, byte_array_cls, NULL);
    }
    return zzdds_java_package_arr(env, reader, &arr, handles_out, valids_out);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeNRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_n(env, reader, max, ss, vs, is_mask, handlesOut, validsOut, 1);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readNRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_n(env, reader, max, ss, vs, is_mask, handlesOut, validsOut, 0);
}

/* ── Instance-scoped / condition-scoped bulk take/read ───────────────────
 *
 * take_instance/read_instance, take_w_condition/read_w_condition,
 * take_next_instance_w_condition/read_next_instance_w_condition -- the raw
 * paths to the matching OMG spec operations. Share zzdds_java_package_arr's
 * output-packaging with take_n_raw/read_n_raw above.
 */

static jobjectArray zzdds_java_take_or_read_n_instance(
    JNIEnv *env, jobject reader_obj, jlong instance_handle, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handles_out, jbooleanArray valids_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    zzdds_raw_sample_array arr;
    int n = is_take
        ? zzdds_take_n_instance_raw(reader, (DDS_InstanceHandle_t)instance_handle, (uint32_t)ss, (uint32_t)vs, (uint32_t)is_mask, (int)max, &arr)
        : zzdds_read_n_instance_raw(reader, (DDS_InstanceHandle_t)instance_handle, (uint32_t)ss, (uint32_t)vs, (uint32_t)is_mask, (int)max, &arr);
    if (n <= 0) {
        jclass byte_array_cls = (*env)->FindClass(env, "[B");
        return byte_array_cls == NULL ? NULL : (*env)->NewObjectArray(env, 0, byte_array_cls, NULL);
    }
    return zzdds_java_package_arr(env, reader, &arr, handles_out, valids_out);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeNInstanceRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jlong instanceHandle, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_n_instance(env, reader, instanceHandle, max, ss, vs, is_mask, handlesOut, validsOut, 1);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readNInstanceRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jlong instanceHandle, jint max, jint ss, jint vs, jint is_mask,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_n_instance(env, reader, instanceHandle, max, ss, vs, is_mask, handlesOut, validsOut, 0);
}

static jobjectArray zzdds_java_take_or_read_w_condition(
    JNIEnv *env, jobject reader_obj, jobject condition_obj, jint max,
    jlongArray handles_out, jbooleanArray valids_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    void *condition = zzdds_java_unbox(env, condition_obj);
    zzdds_raw_sample_array arr;
    int n = is_take
        ? zzdds_take_w_condition_raw(reader, condition, (int)max, &arr)
        : zzdds_read_w_condition_raw(reader, condition, (int)max, &arr);
    if (n <= 0) {
        jclass byte_array_cls = (*env)->FindClass(env, "[B");
        return byte_array_cls == NULL ? NULL : (*env)->NewObjectArray(env, 0, byte_array_cls, NULL);
    }
    return zzdds_java_package_arr(env, reader, &arr, handles_out, valids_out);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeWConditionRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jobject condition, jint max,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_w_condition(env, reader, condition, max, handlesOut, validsOut, 1);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readWConditionRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jobject condition, jint max,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_w_condition(env, reader, condition, max, handlesOut, validsOut, 0);
}

static jobjectArray zzdds_java_take_or_read_next_instance_w_condition(
    JNIEnv *env, jobject reader_obj, jobject condition_obj, jlong prev, jint max,
    jlongArray handles_out, jbooleanArray valids_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    void *condition = zzdds_java_unbox(env, condition_obj);
    zzdds_raw_sample_array arr;
    int n = is_take
        ? zzdds_take_next_instance_w_condition_raw(reader, condition, (DDS_InstanceHandle_t)prev, (int)max, &arr)
        : zzdds_read_next_instance_w_condition_raw(reader, condition, (DDS_InstanceHandle_t)prev, (int)max, &arr);
    if (n <= 0) {
        jclass byte_array_cls = (*env)->FindClass(env, "[B");
        return byte_array_cls == NULL ? NULL : (*env)->NewObjectArray(env, 0, byte_array_cls, NULL);
    }
    return zzdds_java_package_arr(env, reader, &arr, handles_out, valids_out);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeNextInstanceWConditionRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jobject condition, jlong prev, jint max,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_next_instance_w_condition(env, reader, condition, prev, max, handlesOut, validsOut, 1);
}

JNIEXPORT jobjectArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readNextInstanceWConditionRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jobject condition, jlong prev, jint max,
    jlongArray handlesOut, jbooleanArray validsOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read_next_instance_w_condition(env, reader, condition, prev, max, handlesOut, validsOut, 0);
}

/* ── get_key_value / lookup_instance (reader) ─────────────────────────── */

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_getKeyValueReaderRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jlong handle)
{
    (void)self_cls;
    void *r = zzdds_java_unbox(env, reader);
    uint8_t buf[4096];
    size_t len = 0;
    if (zzdds_get_key_value_reader(r, (DDS_InstanceHandle_t)handle, buf, sizeof(buf), &len) != 0) return NULL;
    jbyteArray result = (*env)->NewByteArray(env, (jsize)len);
    (*env)->SetByteArrayRegion(env, result, 0, (jsize)len, (const jbyte *)buf);
    return result;
}

JNIEXPORT jlong JNICALL Java_io_zzdds_runtime_ZzddsRuntime_lookupInstanceReaderRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jbyteArray keyHash)
{
    (void)self_cls;
    void *r = zzdds_java_unbox(env, reader);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    return (jlong)zzdds_lookup_instance_reader(r, (const uint8_t *)hash_buf);
}

/* ── ContentFilteredTopic matching ──────────────────────────────────────
 *
 * Mirrors the C/C++ zzdds_cft_match_sample addition (see zzdds_c.h's doc
 * comment on it): zzdds's own internal CFT filtering only activates when
 * TypeSupport.get_field is wired up, which registerTypeSupport above never
 * does for any binding -- so a DataReader created against a
 * DDS_ContentFilteredTopic still delivers every sample unfiltered unless the
 * app re-checks the filter itself. Rather than reimplementing the filter
 * grammar a second time in Java, this JNI method calls back into a small
 * Java-side FieldAccessor (see ZzddsRuntime.FieldAccessor) once per field
 * the native filter evaluator needs, converting each String/Long result to
 * a zzdds_filter_value, and defers to zzdds's own canonical parser/evaluator
 * via zzdds_cft_match_sample.
 */
#define ZZDDS_JAVA_CFT_MAX_STRINGS 8

typedef struct {
    JNIEnv *env;
    jobject accessor;
    jmethodID get_mid;
    jstring kept[ZZDDS_JAVA_CFT_MAX_STRINGS];
    const char *kept_chars[ZZDDS_JAVA_CFT_MAX_STRINGS];
    size_t kept_count;
} zzdds_java_cft_ctx;

static bool zzdds_java_cft_get(void *ctx_v, const char *field, size_t field_len, zzdds_filter_value *out) {
    zzdds_java_cft_ctx *ctx = (zzdds_java_cft_ctx *)ctx_v;
    JNIEnv *env = ctx->env;

    char field_buf[64];
    if (field_len >= sizeof(field_buf)) return false;
    memcpy(field_buf, field, field_len);
    field_buf[field_len] = '\0';

    jstring jfield = (*env)->NewStringUTF(env, field_buf);
    jobject result = (*env)->CallObjectMethod(env, ctx->accessor, ctx->get_mid, jfield);
    (*env)->DeleteLocalRef(env, jfield);
    if (result == NULL || (*env)->ExceptionCheck(env)) return false;

    jclass long_cls = (*env)->FindClass(env, "java/lang/Long");
    if ((*env)->IsInstanceOf(env, result, long_cls)) {
        jmethodID long_val_mid = (*env)->GetMethodID(env, long_cls, "longValue", "()J");
        out->kind = 0;
        out->i = (int64_t)(*env)->CallLongMethod(env, result, long_val_mid);
        (*env)->DeleteLocalRef(env, result);
        return true;
    }

    /* Anything else must be a String -- kept alive (not released) until the
     * whole zzdds_cft_match_sample call returns, since filter.zig's eval may
     * still be borrowing out->s_ptr from a prior call at that point. */
    if (ctx->kept_count >= ZZDDS_JAVA_CFT_MAX_STRINGS) {
        (*env)->DeleteLocalRef(env, result);
        return false;
    }
    jstring jstr = (jstring)result;
    const char *cstr = (*env)->GetStringUTFChars(env, jstr, NULL);
    out->kind = 2;
    out->s_ptr = (const uint8_t *)cstr;
    out->s_len = strlen(cstr);
    ctx->kept[ctx->kept_count] = jstr;
    ctx->kept_chars[ctx->kept_count] = cstr;
    ctx->kept_count++;
    return true;
}

JNIEXPORT jboolean JNICALL Java_io_zzdds_runtime_ZzddsRuntime_cftMatchSample(
    JNIEnv *env, jclass self_cls, jobject cft, jobject accessor)
{
    (void)self_cls;
    if (cft == NULL) return JNI_TRUE;
    void *c = zzdds_java_unbox(env, cft);

    jclass acc_cls = (*env)->GetObjectClass(env, accessor);
    jmethodID get_mid = (*env)->GetMethodID(env, acc_cls, "get", "(Ljava/lang/String;)Ljava/lang/Object;");
    if (get_mid == NULL) return JNI_TRUE;

    zzdds_java_cft_ctx ctx = { .env = env, .accessor = accessor, .get_mid = get_mid, .kept_count = 0 };
    bool matched = zzdds_cft_match_sample(c, &ctx, zzdds_java_cft_get);

    for (size_t i = 0; i < ctx.kept_count; i++) {
        (*env)->ReleaseStringUTFChars(env, ctx.kept[i], ctx.kept_chars[i]);
        (*env)->DeleteLocalRef(env, ctx.kept[i]);
    }
    return matched ? JNI_TRUE : JNI_FALSE;
}

/* ── zzdds extension-view narrowing ─────────────────────────────────────
 * See ZzddsRuntime.asZzddsDataWriter's javadoc / include/zzdds_c.h's
 * DDS_DataWriter_as_zzdds_DataWriter. Boxes into io.zzdds.ext.DataWriterImpl
 * — cached jclass/jmethodID the same way createFactory() caches
 * DomainParticipantFactoryImpl's. */
JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_asZzddsDataWriter(
    JNIEnv *env, jclass self_cls, jobject writer)
{
    (void)self_cls;
    DDS_DataWriter w = (DDS_DataWriter)zzdds_java_unbox(env, writer);
    zzdds_DataWriter zw = DDS_DataWriter_as_zzdds_DataWriter(w);

    static zzdds_java_class_cache cache = {0};
    if (!zzdds_java_get_or_cache_class(env, &cache, "io/zzdds/ext/DataWriterImpl")) return NULL;
    return (*env)->NewObject(env, cache.cls, cache.ctor, (jlong)(intptr_t)zw);
}
