/* Hand-written native implementation of io.zzdds.runtime.ZzddsRuntime — see
 * that class's javadoc for the contract. Not generated by zidl: zidl only
 * generates the typed <Topic>TypeSupport/DataWriter/DataReader wrappers that
 * call into this fixed surface (see --generate-zzdds-wrappers's Java
 * backend). Compiled into libzzdds_jni.so alongside the generated entity
 * JNI bridge (dcps_jni.c) — see build.zig's -Djava-binding=true section.
 */
#include <jni.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>

#include "dcps.h"
#include "zzdds_c.h"

static void *zzdds_java_unbox(JNIEnv *env, jobject obj) {
    if (obj == NULL) return NULL;
    jclass cls = (*env)->GetObjectClass(env, obj);
    jfieldID fid = (*env)->GetFieldID(env, cls, "ptr_", "J");
    return (void *)(intptr_t)(*env)->GetLongField(env, obj, fid);
}

/* ── Factory bootstrap ──────────────────────────────────────────────────
 *
 * There is no IDL-level "get the singleton DomainParticipantFactory"
 * operation (see zzdds/docs/language-bindings.md) — every zzdds binding
 * bootstraps through this same hand-written zzdds_create_factory() call
 * (C/C++ examples do the same thing via zzdds_c.h directly).
 */
JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_createFactory(JNIEnv *env, jclass self_cls) {
    (void)self_cls;
    zzdds_DomainParticipantFactory zf = zzdds_create_factory();
    if (zzdds_factory_is_nil(zf)) return NULL;
    DDS_DomainParticipantFactory df = zzdds_DomainParticipantFactory_as_DDS_DomainParticipantFactory(zf);

    static jclass cls = NULL;
    static jmethodID ctor = NULL;
    if (cls == NULL) {
        jclass local = (*env)->FindClass(env, "io/zzdds/dcps/DomainParticipantFactoryImpl");
        if (local == NULL) return NULL;
        cls = (jclass)(*env)->NewGlobalRef(env, local);
        (*env)->DeleteLocalRef(env, local);
        ctor = (*env)->GetMethodID(env, cls, "<init>", "(J)V");
    }
    return (*env)->NewObject(env, cls, ctor, (jlong)(intptr_t)df);
}

/* ── TypeSupport registration: one native trampoline, ctx-carrying ──────
 *
 * zzdds_register_type_support_ctx_c (see zzdds_c.h) forwards an opaque ctx
 * to every compute_key_hash call, so — unlike the plain, no-ctx
 * zzdds_register_type_support_c that C/C++/Zig use — one shared trampoline
 * here can dispatch to whichever Java Class<?>/jmethodID a given
 * registration was for, with no fixed slot table and no per-registration
 * lock: each registration gets its own independent heap allocation, freed
 * by zzdds core (via ctx_deinit) exactly when that registration is replaced
 * or its participant is destroyed — see registerTypeSupport/deinit in
 * zzdds/src/dcps/participant.zig, which already reclaims TypeSupport ctx
 * this way for the non-Java C ABI path too.
 */
static JavaVM *zzdds_java_vm = NULL;

static JNIEnv *zzdds_java_get_env(void) {
    JNIEnv *env = NULL;
    if (zzdds_java_vm == NULL) return NULL;
    if ((*zzdds_java_vm)->GetEnv(zzdds_java_vm, (void **)&env, JNI_VERSION_1_6) == JNI_EDETACHED) {
        (*zzdds_java_vm)->AttachCurrentThreadAsDaemon(zzdds_java_vm, (void **)&env, NULL);
    }
    return env;
}

typedef struct {
    jclass cls;    /* global ref */
    jmethodID mid;
} zzdds_java_ts_ctx;

static int zzdds_java_compute_key_hash_ctx(void *ctx_v, const uint8_t *payload, size_t len, uint8_t hash_out[16]) {
    zzdds_java_ts_ctx *ctx = (zzdds_java_ts_ctx *)ctx_v;
    JNIEnv *env = zzdds_java_get_env();
    if (env == NULL) return -1;
    jbyteArray arr = (*env)->NewByteArray(env, (jsize)len);
    (*env)->SetByteArrayRegion(env, arr, 0, (jsize)len, (const jbyte *)payload);
    jbyteArray hash = (jbyteArray)(*env)->CallStaticObjectMethod(env, ctx->cls, ctx->mid, arr);
    if (hash == NULL) return -1;
    (*env)->GetByteArrayRegion(env, hash, 0, 16, (jbyte *)hash_out);
    return 0;
}

/* Called by zzdds core exactly once, when this registration is replaced or
 * its participant is destroyed (see the block comment above). */
static void zzdds_java_ts_ctx_deinit(void *ctx_v) {
    zzdds_java_ts_ctx *ctx = (zzdds_java_ts_ctx *)ctx_v;
    JNIEnv *env = zzdds_java_get_env();
    if (env != NULL) (*env)->DeleteGlobalRef(env, ctx->cls);
    free(ctx);
}

JNIEXPORT jint JNICALL Java_io_zzdds_runtime_ZzddsRuntime_registerTypeSupport(
    JNIEnv *env, jclass self_cls, jobject participant, jstring typeName, jclass typeClass)
{
    (void)self_cls;
    (*env)->GetJavaVM(env, &zzdds_java_vm);

    zzdds_java_ts_ctx *ctx = malloc(sizeof(*ctx));
    if (ctx == NULL) return -1;
    ctx->cls = (jclass)(*env)->NewGlobalRef(env, typeClass);
    ctx->mid = (*env)->GetStaticMethodID(env, typeClass, "computeKeyHashFromCdr", "([B)[B");

    void *p = zzdds_java_unbox(env, participant);
    const char *type_name_c = (*env)->GetStringUTFChars(env, typeName, NULL);
    int rc = zzdds_register_type_support_ctx_c(p, type_name_c, zzdds_java_compute_key_hash_ctx, ctx, zzdds_java_ts_ctx_deinit);
    (*env)->ReleaseStringUTFChars(env, typeName, type_name_c);

    if (rc != 0) {
        /* Registration didn't take — nothing installed it, so nothing will
         * ever call ctx_deinit for it; release what we just allocated
         * ourselves instead of leaking it. */
        (*env)->DeleteGlobalRef(env, ctx->cls);
        free(ctx);
    }
    return rc;
}

/* ── Write/dispose/unregister ───────────────────────────────────────────
 * `kind` matches zzdds_write_kind (0=alive, 1=dispose, 2=unregister) — see
 * ZzddsRuntime.writeRaw's javadoc. */
JNIEXPORT jint JNICALL Java_io_zzdds_runtime_ZzddsRuntime_writeRaw(
    JNIEnv *env, jclass self_cls, jobject writer, jint kind, jbyteArray keyHash, jlong handle, jbyteArray payload)
{
    (void)self_cls;
    void *w = zzdds_java_unbox(env, writer);
    jbyte hash_buf[16];
    (*env)->GetByteArrayRegion(env, keyHash, 0, 16, hash_buf);
    jsize payload_len = (*env)->GetArrayLength(env, payload);
    jbyte *payload_buf = (*env)->GetByteArrayElements(env, payload, NULL);
    int rc = zzdds_write_raw_kind(
        w, (zzdds_write_kind)kind, (const uint8_t *)hash_buf,
        (DDS_InstanceHandle_t)handle, (const uint8_t *)payload_buf, (size_t)payload_len);
    (*env)->ReleaseByteArrayElements(env, payload, payload_buf, JNI_ABORT);
    return rc;
}

/* ── Take/read ───────────────────────────────────────────────────────── */

static jbyteArray zzdds_java_take_or_read(
    JNIEnv *env, jobject reader_obj, jint max_size, jlongArray handle_out, jbooleanArray valid_out, int is_take)
{
    void *reader = zzdds_java_unbox(env, reader_obj);
    uint8_t *buf = malloc((size_t)max_size);
    if (buf == NULL) return NULL;

    zzdds_sample_info info;
    size_t cdr_len = 0;
    int n = is_take
        ? zzdds_take_one_raw(reader, buf, (size_t)max_size, &cdr_len, &info)
        : zzdds_read_one_raw(reader, buf, (size_t)max_size, &cdr_len, &info);
    if (n != 1) {
        free(buf);
        return NULL;
    }

    jlong handle_val = (jlong)info.instance_handle;
    jboolean valid_val = info.valid_data ? JNI_TRUE : JNI_FALSE;
    (*env)->SetLongArrayRegion(env, handle_out, 0, 1, &handle_val);
    (*env)->SetBooleanArrayRegion(env, valid_out, 0, 1, &valid_val);

    jbyteArray result = (*env)->NewByteArray(env, (jsize)cdr_len);
    (*env)->SetByteArrayRegion(env, result, 0, (jsize)cdr_len, (const jbyte *)buf);
    free(buf);
    return result;
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_takeRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read(env, reader, maxSize, handleOut, validOut, 1);
}

JNIEXPORT jbyteArray JNICALL Java_io_zzdds_runtime_ZzddsRuntime_readRaw(
    JNIEnv *env, jclass self_cls, jobject reader, jint maxSize, jlongArray handleOut, jbooleanArray validOut)
{
    (void)self_cls;
    return zzdds_java_take_or_read(env, reader, maxSize, handleOut, validOut, 0);
}

/* ── zzdds extension-view narrowing ─────────────────────────────────────
 * See ZzddsRuntime.asZzddsDataWriter's javadoc / include/zzdds_c.h's
 * DDS_DataWriter_as_zzdds_DataWriter. Boxes into io.zzdds.ext.DataWriterImpl
 * — cached jclass/jmethodID the same way createFactory() caches
 * DomainParticipantFactoryImpl's. */
JNIEXPORT jobject JNICALL Java_io_zzdds_runtime_ZzddsRuntime_asZzddsDataWriter(
    JNIEnv *env, jclass self_cls, jobject writer)
{
    (void)self_cls;
    DDS_DataWriter w = (DDS_DataWriter)zzdds_java_unbox(env, writer);
    zzdds_DataWriter zw = DDS_DataWriter_as_zzdds_DataWriter(w);

    static jclass cls = NULL;
    static jmethodID ctor = NULL;
    if (cls == NULL) {
        jclass local = (*env)->FindClass(env, "io/zzdds/ext/DataWriterImpl");
        if (local == NULL) return NULL;
        cls = (jclass)(*env)->NewGlobalRef(env, local);
        (*env)->DeleteLocalRef(env, local);
        ctor = (*env)->GetMethodID(env, cls, "<init>", "(J)V");
    }
    return (*env)->NewObject(env, cls, ctor, (jlong)(intptr_t)zw);
}
