// Generated by zidl from types.idl — DO NOT EDIT

public class GreeterImpl implements Types.Greeter {
    static { System.loadLibrary("zidl_dds_jni"); }

    private final long ptr_;

    public GreeterImpl(long ptr) { this.ptr_ = ptr; }

    @Override
    public String greet(String name) {
        return n_greet(ptr_, name);
    }
    @Override
    public void reset() {
        n_reset(ptr_);
    }
    @Override
    public int get_count() { return n_get_count(ptr_); }

    private native String n_greet(long ptr, String name);
    private native void n_reset(long ptr);
    private native int n_get_count(long ptr);
}
