// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;

public enum Color {
    RED(0),
    GREEN(1),
    BLUE(2);

    private final int value;
    private Color(int value) { this.value = value; }

    public int getValue() { return value; }

    public static Color valueOf(int v) {
        for (Color _e : values()) { if (_e.value == v) return _e; }
        throw new RuntimeException("Unknown Color value: " + v);
    }
} // Color

