// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;
import static TypesCdrUtils.*;

public class Frame implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private int seq_num;
    private String topic;

    public Frame() {
        this.seq_num = 0;
        this.topic = "";
    }

    public Frame(int seq_num, String topic) {
        this.seq_num = seq_num;
        this.topic = topic;
    }

    public int get_seq_num() { return seq_num; }
    public void set_seq_num(int seq_num) { this.seq_num = seq_num; }

    public String get_topic() { return topic; }
    public void set_topic(String topic) { this.topic = topic; }

    public static final boolean HAS_KEY = false;

    public void serialize(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4);
        int _dhPos = _buf.position(); _buf.putInt(0);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.seq_num);
        _cdrWriteString(_buf, _cdrBase, this.topic);
        _buf.putInt(_dhPos, _buf.position() - _dhPos - 4);
    }

    public static Frame deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Frame _out = new Frame();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt(); // skip DHEADER
        _cdrAlign(_buf, _cdrBase, 4); _out.seq_num = _buf.getInt();
        _out.topic = _cdrReadString(_buf, _cdrBase);
        return _out;
    }

    public static void skip(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); int _end = _buf.position() + 4 + _buf.getInt();
        _buf.position(_end);
    }
} // Frame

