// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;

public interface Greeter {
    String greet(String name);
    void reset();
    int get_count();
} // interface Greeter

