// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;
import static TypesCdrUtils.*;

public class Point implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private int x;
    private int y;

    public Point() {
        this.x = 0;
        this.y = 0;
    }

    public Point(int x, int y) {
        this.x = x;
        this.y = y;
    }

    public int get_x() { return x; }
    public void set_x(int x) { this.x = x; }

    public int get_y() { return y; }
    public void set_y(int y) { this.y = y; }

    public static final boolean HAS_KEY = false;

    public void serialize(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.x);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.y);
    }

    public static Point deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Point _out = new Point();
        _cdrAlign(_buf, _cdrBase, 4); _out.x = _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _out.y = _buf.getInt();
        return _out;
    }

    public static void skip(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
    }
} // Point

