// Generated by zidl from types.idl — DO NOT EDIT

import java.util.List;
import java.util.ArrayList;
import static TypesCdrUtils.*;

public class Sample implements java.io.Serializable {
    private static final long serialVersionUID = 1L;
    private int id;
    private boolean b;
    private byte u8_val;
    private short s16_val;
    private short u16_val;
    private int s32_val;
    private int u32_val;
    private long s64_val;
    private long u64_val;
    private float f32_val;
    private double f64_val;
    private String str;
    private String bstr;
    private java.util.List<Integer> nums;
    private int[] arr;
    private Color clr;
    private Point nested;

    public Sample() {
        this.id = 0;
        this.b = false;
        this.u8_val = 0;
        this.s16_val = 0;
        this.u16_val = 0;
        this.s32_val = 0;
        this.u32_val = 0;
        this.s64_val = 0;
        this.u64_val = 0;
        this.f32_val = 0.0f;
        this.f64_val = 0.0;
        this.str = "";
        this.bstr = "";
        this.nums = new java.util.ArrayList<>();
        this.arr = new int[3];
        this.clr = Color.values()[0];
        this.nested = new Point();
    }

    public Sample(int id, boolean b, byte u8_val, short s16_val, short u16_val, int s32_val, int u32_val, long s64_val, long u64_val, float f32_val, double f64_val, String str, String bstr, java.util.List<Integer> nums, int[] arr, Color clr, Point nested) {
        this.id = id;
        this.b = b;
        this.u8_val = u8_val;
        this.s16_val = s16_val;
        this.u16_val = u16_val;
        this.s32_val = s32_val;
        this.u32_val = u32_val;
        this.s64_val = s64_val;
        this.u64_val = u64_val;
        this.f32_val = f32_val;
        this.f64_val = f64_val;
        this.str = str;
        this.bstr = bstr;
        this.nums = nums;
        this.arr = arr;
        this.clr = clr;
        this.nested = nested;
    }

    public int get_id() { return id; }
    public void set_id(int id) { this.id = id; }

    public boolean get_b() { return b; }
    public void set_b(boolean b) { this.b = b; }

    public byte get_u8_val() { return u8_val; }
    public void set_u8_val(byte u8_val) { this.u8_val = u8_val; }

    public short get_s16_val() { return s16_val; }
    public void set_s16_val(short s16_val) { this.s16_val = s16_val; }

    public short get_u16_val() { return u16_val; }
    public void set_u16_val(short u16_val) { this.u16_val = u16_val; }

    public int get_s32_val() { return s32_val; }
    public void set_s32_val(int s32_val) { this.s32_val = s32_val; }

    public int get_u32_val() { return u32_val; }
    public void set_u32_val(int u32_val) { this.u32_val = u32_val; }

    public long get_s64_val() { return s64_val; }
    public void set_s64_val(long s64_val) { this.s64_val = s64_val; }

    public long get_u64_val() { return u64_val; }
    public void set_u64_val(long u64_val) { this.u64_val = u64_val; }

    public float get_f32_val() { return f32_val; }
    public void set_f32_val(float f32_val) { this.f32_val = f32_val; }

    public double get_f64_val() { return f64_val; }
    public void set_f64_val(double f64_val) { this.f64_val = f64_val; }

    public String get_str() { return str; }
    public void set_str(String str) { this.str = str; }

    public String get_bstr() { return bstr; }
    public void set_bstr(String bstr) { this.bstr = bstr; }

    public java.util.List<Integer> get_nums() { return nums; }
    public void set_nums(java.util.List<Integer> nums) { this.nums = nums; }

    public int[] get_arr() { return arr; }
    public void set_arr(int[] arr) { this.arr = arr; }

    public Color get_clr() { return clr; }
    public void set_clr(Color clr) { this.clr = clr; }

    public Point get_nested() { return nested; }
    public void set_nested(Point nested) { this.nested = nested; }

    public static final boolean HAS_KEY = true;

    public void serialize(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
        _buf.put((byte)(this.b ? 1 : 0));
        _buf.put(this.u8_val);
        _cdrAlign(_buf, _cdrBase, 2); _buf.putShort(this.s16_val);
        _cdrAlign(_buf, _cdrBase, 2); _buf.putShort(this.u16_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.s32_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.u32_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putLong(this.s64_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putLong(this.u64_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putFloat(this.f32_val);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putDouble(this.f64_val);
        _cdrWriteString(_buf, _cdrBase, this.str);
        _cdrWriteString(_buf, _cdrBase, this.bstr);
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.nums.size());
        for (Integer _e : this.nums) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(_e);
        }
        for (int _d0 = 0; _d0 < 3; _d0++) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.arr[_d0]);
        }
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.clr.getValue());
        this.nested.serialize(_buf, _cdrBase);
    }

    public static Sample deserializeFrom(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Sample _out = new Sample();
        _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
        _out.b = _buf.get() != 0;
        _out.u8_val = _buf.get();
        _cdrAlign(_buf, _cdrBase, 2); _out.s16_val = _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 2); _out.u16_val = _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 4); _out.s32_val = _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _out.u32_val = _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _out.s64_val = _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _out.u64_val = _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _out.f32_val = _buf.getFloat();
        _cdrAlign(_buf, _cdrBase, 4); _out.f64_val = _buf.getDouble();
        _out.str = _cdrReadString(_buf, _cdrBase);
        _out.bstr = _cdrReadString(_buf, _cdrBase);
        _cdrAlign(_buf, _cdrBase, 4); int _n__out_nums = _buf.getInt();
        _out.nums = new java.util.ArrayList<>(_n__out_nums);
        for (int _i__out_nums = 0; _i__out_nums < _n__out_nums; _i__out_nums++) {
            _cdrAlign(_buf, _cdrBase, 4); _out.nums.add(_buf.getInt());
        }
        for (int _d0 = 0; _d0 < 3; _d0++) {
            _cdrAlign(_buf, _cdrBase, 4); _out.arr[_d0] = _buf.getInt();
        }
        _cdrAlign(_buf, _cdrBase, 4); _out.clr = Color.valueOf(_buf.getInt());
        _out.nested = Point.deserializeFrom(_buf, _cdrBase);
        return _out;
    }

    public static void skip(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _buf.get();
        _buf.get();
        _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrReadString(_buf, _cdrBase);
        _cdrReadString(_buf, _cdrBase);
        { _cdrAlign(_buf, _cdrBase, 4); int _n = _buf.getInt();
          for (int _i = 0; _i < _n; _i++) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
          }
        }
        for (int _sk0 = 0; _sk0 < 3; _sk0++) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        }
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        Point.skip(_buf, _cdrBase);
    }

    protected void serializeKeyFields(java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4); _buf.putInt(this.id);
    }

    public void serializeKey(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        serializeKeyFields(_buf, _cdrBase);
    }

    public static Sample deserializeKey(java.nio.ByteBuffer _buf, int _cdrBase) {
        _buf.order(java.nio.ByteOrder.LITTLE_ENDIAN);
        Sample _out = new Sample();
        deserializeKeyInto(_out, _buf, _cdrBase);
        return _out;
    }

    protected static void deserializeKeyInto(Sample _out, java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4); _out.id = _buf.getInt();
        _buf.get();
        _buf.get();
        _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 2); _buf.getShort();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        _cdrAlign(_buf, _cdrBase, 4); _buf.getLong();
        _cdrReadString(_buf, _cdrBase);
        _cdrReadString(_buf, _cdrBase);
        { _cdrAlign(_buf, _cdrBase, 4); int _n = _buf.getInt();
          for (int _i = 0; _i < _n; _i++) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
          }
        }
        for (int _sk0 = 0; _sk0 < 3; _sk0++) {
            _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        }
        _cdrAlign(_buf, _cdrBase, 4); _buf.getInt();
        Point.skip(_buf, _cdrBase);
    }

    public byte[] computeKeyHash() {
        int _cap = 256;
        while (true) {
            java.nio.ByteBuffer _buf = java.nio.ByteBuffer.allocate(_cap).order(java.nio.ByteOrder.BIG_ENDIAN);
            try {
                serializeKeyFields(_buf, 0);
                return _cdrComputeKeyHash(_buf);
            } catch (java.nio.BufferOverflowException _e) {
                _cap *= 2;
            }
        }
    }
} // Sample

