// Generated by zidl from types.idl — DO NOT EDIT

public class TypesCdrUtils {
    public static void _cdrAlign(java.nio.ByteBuffer _buf, int _cdrBase, int _align) {
        if (_align <= 1) return;
        int _p = (_buf.position() - _cdrBase) % _align;
        if (_p != 0) { for (int _i = 0; _i < _align - _p; _i++) _buf.put((byte)0); }
    }
    public static void _cdrWriteString(java.nio.ByteBuffer _buf, int _cdrBase, String _s) {
        _cdrAlign(_buf, _cdrBase, 4);
        byte[] _b = _s.getBytes(java.nio.charset.StandardCharsets.UTF_8);
        _buf.putInt(_b.length + 1);
        _buf.put(_b);
        _buf.put((byte)0);
    }
    public static String _cdrReadString(java.nio.ByteBuffer _buf, int _cdrBase) {
        _cdrAlign(_buf, _cdrBase, 4);
        int _len = _buf.getInt() - 1;
        byte[] _b = new byte[_len];
        _buf.get(_b);
        _buf.get(); // null terminator
        return new String(_b, java.nio.charset.StandardCharsets.UTF_8);
    }
    public static byte[] _cdrComputeKeyHash(java.nio.ByteBuffer _buf) {
        int _len = _buf.position();
        byte[] _key = new byte[_len];
        _buf.position(0); _buf.get(_key);
        if (_len <= 16) {
            byte[] _out = new byte[16];
            System.arraycopy(_key, 0, _out, 0, _len);
            return _out;
        }
        try { return java.security.MessageDigest.getInstance("MD5").digest(_key); }
        catch (java.security.NoSuchAlgorithmException _e) { throw new IllegalStateException(_e); }
    }
}
