/* Generated by zidl from types.idl — DO NOT EDIT */

#include <jni.h>
#include <stdint.h>
#include <stddef.h>

/* ── interface Greeter ── */

/* Zig DDS runtime exports (provided at link time). */
extern const char * zidl_Greeter_greet(void *ptr, const char * name);
extern void zidl_Greeter_reset(void *ptr);
extern int32_t zidl_Greeter_get_count(void *ptr);
extern void zidl_Greeter_deinit(void *ptr);

/* JNI bridge for GreeterImpl */
JNIEXPORT jstring JNICALL Java_GreeterImpl_n_1greet(
    JNIEnv *env, jobject self, jlong ptr, jstring name)
{
    (void)env; (void)self;
    return (jstring)zidl_Greeter_greet((void *)(intptr_t)ptr, (const char *)name);
}

JNIEXPORT void JNICALL Java_GreeterImpl_n_1reset(
    JNIEnv *env, jobject self, jlong ptr)
{
    (void)env; (void)self;
    zidl_Greeter_reset((void *)(intptr_t)ptr);
}

JNIEXPORT jint JNICALL Java_GreeterImpl_n_1get_1count(
    JNIEnv *env, jobject self, jlong ptr)
{
    (void)env; (void)self;
    return (jint)zidl_Greeter_get_count((void *)(intptr_t)ptr);
}

JNIEXPORT void JNICALL Java_GreeterImpl_deinit(
    JNIEnv *env, jobject self, jlong ptr)
{
    (void)env; (void)self;
    zidl_Greeter_deinit((void *)(intptr_t)ptr);
}

