//! C-ABI TypeSupport registration shim.
//!
//! Allows C (and any language with C FFI — Python ctypes, C# P/Invoke, Rust
//! extern "C", etc.) to register CDR-capable types with a DomainParticipant.
//! The primary use case is passing the `<Type>_compute_key_hash_from_cdr`/
//! `<Type>_get_field_from_cdr` functions generated by `zidl -b c` as the
//! compute_key_hash/get_field callbacks.
//!
//! Usage from C:
//!
//!   #include "zzdds_c.h"
//!
//!   zzdds_register_type_support(
//!       participant,
//!       "ShapeType",
//!       ShapeType_compute_key_hash_from_cdr,
//!       ShapeType_get_field_from_cdr
//!   );

const std = @import("std");
const DDS = @import("zzdds_generated").DDS;
const participant_mod = @import("../dcps/participant.zig");
const TypeSupport = participant_mod.TypeSupport;
const DomainParticipantImpl = participant_mod.DomainParticipantImpl;
const filter_mod = @import("../dcps/filter.zig");
const nil = @import("../dcps/nil.zig");
const zidl_rt = @import("zidl_rt");
const extensions = @import("extensions.zig");

/// Discriminated field value shared with `zzdds_cft_match_sample`'s
/// `zzdds_filter_value` (see `extensions.zig`) — same C-ABI struct layout,
/// declared once there and reused here rather than duplicated.
pub const ZzddsFilterValue = extensions.ZzddsFilterValue;

fn zzddsFilterValueToZig(v: ZzddsFilterValue) ?filter_mod.FilterValue {
    return switch (v.kind) {
        0 => filter_mod.FilterValue{ .int = v.i },
        1 => filter_mod.FilterValue{ .float = v.f },
        2 => filter_mod.FilterValue{ .string = (v.s_ptr orelse return null)[0..v.s_len] },
        3 => filter_mod.FilterValue{ .float32 = @floatCast(v.f) },
        else => null,
    };
}

/// C-compatible compute_key_hash function type.
/// Matches the signature of `<Type>_compute_key_hash_from_cdr` generated by
/// `zidl -b c` (and `zidl -b cpp`).
///
/// Returns 0 (ZIDL_CDR_OK) on success, non-zero on parse failure.
pub const ZzddsComputeKeyHashFn = *const fn (
    payload: [*]const u8,
    len: usize,
    hash_out: *[16]u8,
) callconv(.c) c_int;

/// C-compatible get_field_from_cdr function type. Matches the signature of
/// `<Type>_get_field_from_cdr` generated by `zidl -b c`/`-b cpp`. See
/// `zzdds_get_field_from_cdr_fn`'s doc comment in zzdds_c.h for the
/// `scratch`/`scratch_len` contract (a matched string's bytes must be copied
/// there, not returned as a pointer into a local).
pub const ZzddsGetFieldFromCdrFn = *const fn (
    payload: [*]const u8,
    payload_len: usize,
    field: [*]const u8,
    field_len: usize,
    out: *ZzddsFilterValue,
    scratch: [*]u8,
    scratch_len: usize,
) callconv(.c) bool;

/// Per-registration adapter. Heap-allocated via the owning participant's
/// allocator (impl.alloc) when zzdds_register_type_support is called; freed
/// with the same allocator when the participant deinits or replaces this
/// registration.
///
/// Always allocated, even when both callbacks are null (a keyless,
/// non-filterable type) — a single unconditional shape here is simpler than
/// forking on "which callbacks were actually given" the way this used to
/// (before get_field existed) skip allocating anything at all for a null
/// compute_key_hash_fn. That old fast path would have been wrong anyway once
/// a keyless type could still want get_field_fn (a keyless struct can have
/// non-key fields a CFT expression filters on).
const CTypeSupportAdapter = struct {
    alloc: std.mem.Allocator,
    key_hash_fn: ?ZzddsComputeKeyHashFn,
    get_field_fn: ?ZzddsGetFieldFromCdrFn,

    fn computeKeyHash(ctx: *anyopaque, payload: []const u8) [16]u8 {
        const self: *CTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        var hash: [16]u8 = std.mem.zeroes([16]u8);
        if (self.key_hash_fn) |f| _ = f(payload.ptr, payload.len, &hash);
        return hash;
    }

    fn getField(ctx: *anyopaque, payload: []const u8, field: []const u8, scratch: []u8) ?filter_mod.FilterValue {
        const self: *CTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        const f = self.get_field_fn orelse return null;
        var out: ZzddsFilterValue = .{};
        if (!f(payload.ptr, payload.len, field.ptr, field.len, &out, scratch.ptr, scratch.len)) return null;
        return zzddsFilterValueToZig(out);
    }

    fn deinitAdapter(ctx: *anyopaque) void {
        const self: *CTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        self.alloc.destroy(self);
    }
};

/// Register a C-ABI TypeSupport with a DomainParticipant.
///
/// @param participant          Public DDS_DomainParticipant handle (the boxed
///                             C-ABI opaque pointer, per zzdds_c.h's
///                             DDS_DomainParticipant typedef -- NOT the native
///                             Zig fat-pointer struct).
/// @param type_name            Null-terminated type name string.
/// @param compute_key_hash_fn  C function that computes the key hash from raw
///                             CDR bytes (encap header included).  Pass NULL
///                             for keyless types.
/// @param get_field_fn         C function that extracts a named field from raw
///                             CDR bytes, for automatic ContentFilteredTopic
///                             filtering.  Pass NULL if the type has no
///                             filterable fields.
///
/// Returns 0 on success, -1 if the internal allocation failed.
pub export fn zzdds_register_type_support(
    participant: *anyopaque,
    type_name: [*:0]const u8,
    compute_key_hash_fn: ?ZzddsComputeKeyHashFn,
    get_field_fn: ?ZzddsGetFieldFromCdrFn,
) callconv(.c) c_int {
    // zidl_rt.unboxAs dereferences its argument unconditionally -- a literal
    // NULL passed by a C caller (a normal, expected "no object" value in C,
    // not UB) must be caught before unboxing, not after; nil.isNil only
    // catches an *already-unboxed* entity's ptr == NIL_PTR sentinel, which a
    // raw NULL C pointer would never reach without crashing first.
    if (@intFromPtr(participant) == 0) return -1;
    const p = zidl_rt.unboxAsView(DDS.DomainParticipant, participant);
    if (nil.isNil(p)) return -1;
    const impl: *DomainParticipantImpl = @ptrCast(@alignCast(p.ptr));
    const name = std.mem.span(type_name);

    const adapter = impl.alloc.create(CTypeSupportAdapter) catch return -1;
    adapter.* = .{ .alloc = impl.alloc, .key_hash_fn = compute_key_hash_fn, .get_field_fn = get_field_fn };
    if (!impl.registerTypeSupport(name, TypeSupport{
        .ctx = adapter,
        .compute_key_hash = CTypeSupportAdapter.computeKeyHash,
        // Per this entry point's contract, a keyed type passes its generated
        // `<Type>_compute_key_hash_from_cdr`; a keyless type passes NULL.
        .has_key = compute_key_hash_fn != null,
        .get_field = if (get_field_fn != null) CTypeSupportAdapter.getField else null,
        .deinit = CTypeSupportAdapter.deinitAdapter,
    })) {
        impl.alloc.destroy(adapter);
        return -1;
    }

    return 0;
}

/// `ctx`-carrying compute_key_hash function type.
///
/// Unlike `ZzddsComputeKeyHashFn`, this variant carries a caller-owned `ctx`
/// through to every call — needed by any binding that can't generate a fresh,
/// uniquely-addressed native function per registered type the way `zidl -b c`/
/// `-b cpp` do (e.g. classic JNI: a Java `Class<?>` has no native function
/// pointer of its own, so one shared trampoline needs `ctx` to know which
/// class/method to dispatch to). C/C++/Zig callers don't need this — keep
/// using `zzdds_register_type_support` above.
pub const ZzddsComputeKeyHashCtxFn = *const fn (
    ctx: ?*anyopaque,
    payload: [*]const u8,
    len: usize,
    hash_out: *[16]u8,
) callconv(.c) c_int;

/// `ctx`-carrying get_field_from_cdr function type — see
/// `ZzddsComputeKeyHashCtxFn`'s doc comment for why this exists.
pub const ZzddsGetFieldFromCdrCtxFn = *const fn (
    ctx: ?*anyopaque,
    payload: [*]const u8,
    payload_len: usize,
    field: [*]const u8,
    field_len: usize,
    out: *ZzddsFilterValue,
    scratch: [*]u8,
    scratch_len: usize,
) callconv(.c) bool;

/// Per-registration adapter forwarding to a caller-supplied `ctx` (as opposed
/// to `CTypeSupportAdapter`, which wraps bare, type-specific C functions that
/// need no ctx of their own). Heap-allocated when
/// `zzdds_register_type_support_ctx` is called; freed (calling the caller's
/// own `user_deinit` first, if any) when the participant deinits or replaces
/// this TypeSupport registration — see `DomainParticipantImpl.deinit`/
/// `registerTypeSupport` in `src/dcps/participant.zig`, unchanged by this.
const CtxTypeSupportAdapter = struct {
    alloc: std.mem.Allocator,
    key_hash_fn: ?ZzddsComputeKeyHashCtxFn,
    get_field_fn: ?ZzddsGetFieldFromCdrCtxFn,
    user_ctx: ?*anyopaque,
    user_deinit: ?*const fn (?*anyopaque) callconv(.c) void,

    fn computeKeyHash(ctx: *anyopaque, payload: []const u8) [16]u8 {
        const self: *CtxTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        var hash: [16]u8 = std.mem.zeroes([16]u8);
        if (self.key_hash_fn) |f| _ = f(self.user_ctx, payload.ptr, payload.len, &hash);
        return hash;
    }

    fn getField(ctx: *anyopaque, payload: []const u8, field: []const u8, scratch: []u8) ?filter_mod.FilterValue {
        const self: *CtxTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        const f = self.get_field_fn orelse return null;
        var out: ZzddsFilterValue = .{};
        if (!f(self.user_ctx, payload.ptr, payload.len, field.ptr, field.len, &out, scratch.ptr, scratch.len)) return null;
        return zzddsFilterValueToZig(out);
    }

    fn deinitAdapter(ctx: *anyopaque) void {
        const self: *CtxTypeSupportAdapter = @ptrCast(@alignCast(ctx));
        if (self.user_deinit) |f| f(self.user_ctx);
        self.alloc.destroy(self);
    }
};

/// Register a C-ABI TypeSupport with a DomainParticipant, with a `ctx`
/// forwarded to `compute_key_hash_fn`/`get_field_fn` on every call (the SAME
/// ctx for both — one shared per-registration context, not two).
///
/// @param participant          Same as `zzdds_register_type_support`.
/// @param type_name            Null-terminated type name string.
/// @param compute_key_hash_fn  Function computing the key hash from raw CDR
///                             bytes, given the `ctx` below. Pass NULL for
///                             keyless types.
/// @param get_field_fn         Function extracting a named field from raw CDR
///                             bytes, given the `ctx` below. Pass NULL if the
///                             type has no filterable fields.
/// @param ctx                  Opaque, caller-owned context passed to every
///                             `compute_key_hash_fn`/`get_field_fn` call for
///                             this registration.
/// @param ctx_deinit           Optional cleanup for `ctx`, called exactly once
///                             when this registration is replaced or its
///                             participant is destroyed. NULL if `ctx` needs
///                             no cleanup (e.g. it isn't heap-allocated).
///
/// Returns 0 on success, -1 if the internal allocation failed.
pub export fn zzdds_register_type_support_ctx(
    participant: *anyopaque,
    type_name: [*:0]const u8,
    compute_key_hash_fn: ?ZzddsComputeKeyHashCtxFn,
    get_field_fn: ?ZzddsGetFieldFromCdrCtxFn,
    ctx: ?*anyopaque,
    ctx_deinit: ?*const fn (?*anyopaque) callconv(.c) void,
) callconv(.c) c_int {
    if (@intFromPtr(participant) == 0) return -1;
    const p = zidl_rt.unboxAsView(DDS.DomainParticipant, participant);
    if (nil.isNil(p)) return -1;
    const impl: *DomainParticipantImpl = @ptrCast(@alignCast(p.ptr));
    const name = std.mem.span(type_name);

    const adapter = impl.alloc.create(CtxTypeSupportAdapter) catch return -1;
    adapter.* = .{ .alloc = impl.alloc, .key_hash_fn = compute_key_hash_fn, .get_field_fn = get_field_fn, .user_ctx = ctx, .user_deinit = ctx_deinit };
    if (!impl.registerTypeSupport(name, TypeSupport{
        .ctx = adapter,
        .compute_key_hash = CtxTypeSupportAdapter.computeKeyHash,
        .has_key = compute_key_hash_fn != null,
        .get_field = if (get_field_fn != null) CtxTypeSupportAdapter.getField else null,
        .deinit = CtxTypeSupportAdapter.deinitAdapter,
    })) {
        impl.alloc.destroy(adapter);
        return -1;
    }

    return 0;
}
