//! C-ABI TypeSupport registration shim.
//!
//! Allows C (and any language with C FFI — Python ctypes, C# P/Invoke, Rust
//! extern "C", etc.) to register CDR-capable types with a DomainParticipant.
//! The primary use case is passing the `<Type>_compute_key_hash_from_cdr`
//! function generated by `zidl -b c` as the compute_key_hash callback.
//!
//! Usage from C:
//!
//!   #include "zzdds_c.h"
//!
//!   zzdds_register_type_support_c(
//!       participant,
//!       "ShapeType",
//!       ShapeType_compute_key_hash_from_cdr
//!   );

const std = @import("std");
const DDS = @import("zzdds_generated").DDS;
const participant_mod = @import("../dcps/participant.zig");
const TypeSupport = participant_mod.TypeSupport;
const DomainParticipantImpl = participant_mod.DomainParticipantImpl;
const nil = @import("../dcps/nil.zig");
const zidl_rt = @import("zidl_rt");

/// C-compatible compute_key_hash function type.
/// Matches the signature of `<Type>_compute_key_hash_from_cdr` generated by
/// `zidl -b c` (and `zidl -b cpp`).
///
/// Returns 0 (ZIDL_CDR_OK) on success, non-zero on parse failure.
pub const ZzddsComputeKeyHashFn = *const fn (
    payload: [*]const u8,
    len: usize,
    hash_out: *[16]u8,
) callconv(.c) c_int;

/// Per-registration adapter.  Heap-allocated via std.heap.c_allocator when
/// zzdds_register_type_support_c is called; freed when the participant deinits.
const CKeyHashAdapter = struct {
    c_fn: ZzddsComputeKeyHashFn,

    fn computeKeyHash(ctx: *anyopaque, payload: []const u8) [16]u8 {
        const self: *CKeyHashAdapter = @ptrCast(@alignCast(ctx));
        var hash: [16]u8 = std.mem.zeroes([16]u8);
        _ = self.c_fn(payload.ptr, payload.len, &hash);
        return hash;
    }

    fn deinitAdapter(ctx: *anyopaque) void {
        const self: *CKeyHashAdapter = @ptrCast(@alignCast(ctx));
        std.heap.c_allocator.destroy(self);
    }
};

/// Register a C-ABI TypeSupport with a DomainParticipant.
///
/// @param participant          Public DDS_DomainParticipant handle (the boxed
///                             C-ABI opaque pointer, per zzdds_c.h's
///                             DDS_DomainParticipant typedef -- NOT the native
///                             Zig fat-pointer struct).
/// @param type_name            Null-terminated type name string.
/// @param compute_key_hash_fn  C function that computes the key hash from raw
///                             CDR bytes (encap header included).  Pass NULL
///                             for keyless types.
///
/// Returns 0 on success, -1 if the internal allocation failed.
pub export fn zzdds_register_type_support_c(
    participant: *anyopaque,
    type_name: [*:0]const u8,
    compute_key_hash_fn: ?ZzddsComputeKeyHashFn,
) callconv(.c) c_int {
    // zidl_rt.unboxAs dereferences its argument unconditionally -- a literal
    // NULL passed by a C caller (a normal, expected "no object" value in C,
    // not UB) must be caught before unboxing, not after; nil.isNil only
    // catches an *already-unboxed* entity's ptr == NIL_PTR sentinel, which a
    // raw NULL C pointer would never reach without crashing first.
    if (@intFromPtr(participant) == 0) return -1;
    const p = zidl_rt.unboxAs(DDS.DomainParticipant, participant);
    if (nil.isNil(p)) return -1;
    const impl: *DomainParticipantImpl = @ptrCast(@alignCast(p.ptr));
    const name = std.mem.span(type_name);

    if (compute_key_hash_fn) |c_fn| {
        const adapter = std.heap.c_allocator.create(CKeyHashAdapter) catch return -1;
        adapter.* = .{ .c_fn = c_fn };
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = adapter,
            .compute_key_hash = CKeyHashAdapter.computeKeyHash,
            .deinit = CKeyHashAdapter.deinitAdapter,
        })) {
            std.heap.c_allocator.destroy(adapter);
            return -1;
        }
    } else {
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = undefined,
            .compute_key_hash = struct {
                fn f(_: *anyopaque, _: []const u8) [16]u8 {
                    return std.mem.zeroes([16]u8);
                }
            }.f,
        })) return -1;
    }

    return 0;
}

/// `ctx`-carrying compute_key_hash function type.
///
/// Unlike `ZzddsComputeKeyHashFn`, this variant carries a caller-owned `ctx`
/// through to every call — needed by any binding that can't generate a fresh,
/// uniquely-addressed native function per registered type the way `zidl -b c`/
/// `-b cpp` do (e.g. classic JNI: a Java `Class<?>` has no native function
/// pointer of its own, so one shared trampoline needs `ctx` to know which
/// class/method to dispatch to). C/C++/Zig callers don't need this — keep
/// using `zzdds_register_type_support_c` above.
pub const ZzddsComputeKeyHashCtxFn = *const fn (
    ctx: ?*anyopaque,
    payload: [*]const u8,
    len: usize,
    hash_out: *[16]u8,
) callconv(.c) c_int;

/// Per-registration adapter forwarding to a caller-supplied `ctx` (as opposed
/// to `CKeyHashAdapter`, which wraps a bare, type-specific C function that
/// needs no ctx of its own). Heap-allocated when
/// `zzdds_register_type_support_ctx_c` is called; freed (calling the caller's
/// own `user_deinit` first, if any) when the participant deinits or replaces
/// this TypeSupport registration — see `DomainParticipantImpl.deinit`/
/// `registerTypeSupport` in `src/dcps/participant.zig`, unchanged by this.
const CtxKeyHashAdapter = struct {
    c_fn: ZzddsComputeKeyHashCtxFn,
    user_ctx: ?*anyopaque,
    user_deinit: ?*const fn (?*anyopaque) callconv(.c) void,

    fn computeKeyHash(ctx: *anyopaque, payload: []const u8) [16]u8 {
        const self: *CtxKeyHashAdapter = @ptrCast(@alignCast(ctx));
        var hash: [16]u8 = std.mem.zeroes([16]u8);
        _ = self.c_fn(self.user_ctx, payload.ptr, payload.len, &hash);
        return hash;
    }

    fn deinitAdapter(ctx: *anyopaque) void {
        const self: *CtxKeyHashAdapter = @ptrCast(@alignCast(ctx));
        if (self.user_deinit) |f| f(self.user_ctx);
        std.heap.c_allocator.destroy(self);
    }
};

/// Register a C-ABI TypeSupport with a DomainParticipant, with a `ctx`
/// forwarded to `compute_key_hash_fn` on every call.
///
/// @param participant          Same as `zzdds_register_type_support_c`.
/// @param type_name            Null-terminated type name string.
/// @param compute_key_hash_fn  Function computing the key hash from raw CDR
///                             bytes, given the `ctx` below. Pass NULL for
///                             keyless types (ctx/ctx_deinit are ignored then).
/// @param ctx                  Opaque, caller-owned context passed to every
///                             `compute_key_hash_fn` call for this registration.
/// @param ctx_deinit           Optional cleanup for `ctx`, called exactly once
///                             when this registration is replaced or its
///                             participant is destroyed. NULL if `ctx` needs
///                             no cleanup (e.g. it isn't heap-allocated).
///
/// Returns 0 on success, -1 if the internal allocation failed.
pub export fn zzdds_register_type_support_ctx_c(
    participant: *anyopaque,
    type_name: [*:0]const u8,
    compute_key_hash_fn: ?ZzddsComputeKeyHashCtxFn,
    ctx: ?*anyopaque,
    ctx_deinit: ?*const fn (?*anyopaque) callconv(.c) void,
) callconv(.c) c_int {
    if (@intFromPtr(participant) == 0) return -1;
    const p = zidl_rt.unboxAs(DDS.DomainParticipant, participant);
    if (nil.isNil(p)) return -1;
    const impl: *DomainParticipantImpl = @ptrCast(@alignCast(p.ptr));
    const name = std.mem.span(type_name);

    if (compute_key_hash_fn) |c_fn| {
        const adapter = std.heap.c_allocator.create(CtxKeyHashAdapter) catch return -1;
        adapter.* = .{ .c_fn = c_fn, .user_ctx = ctx, .user_deinit = ctx_deinit };
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = adapter,
            .compute_key_hash = CtxKeyHashAdapter.computeKeyHash,
            .deinit = CtxKeyHashAdapter.deinitAdapter,
        })) {
            std.heap.c_allocator.destroy(adapter);
            return -1;
        }
    } else {
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = undefined,
            .compute_key_hash = struct {
                fn f(_: *anyopaque, _: []const u8) [16]u8 {
                    return std.mem.zeroes([16]u8);
                }
            }.f,
        })) return -1;
    }

    return 0;
}
