//! C-ABI TypeSupport registration shim.
//!
//! Allows C (and any language with C FFI — Python ctypes, C# P/Invoke, Rust
//! extern "C", etc.) to register CDR-capable types with a DomainParticipant.
//! The primary use case is passing the `<Type>_compute_key_hash_from_cdr`
//! function generated by `zidl -b c` as the compute_key_hash callback.
//!
//! Usage from C:
//!
//!   #include "zzdds_c.h"
//!
//!   zzdds_register_type_support_c(
//!       participant,
//!       "ShapeType",
//!       ShapeType_compute_key_hash_from_cdr
//!   );

const std = @import("std");
const DDS = @import("zzdds_generated").DDS;
const participant_mod = @import("../dcps/participant.zig");
const TypeSupport = participant_mod.TypeSupport;
const DomainParticipantImpl = participant_mod.DomainParticipantImpl;
const nil = @import("../dcps/nil.zig");

/// C-compatible compute_key_hash function type.
/// Matches the signature of `<Type>_compute_key_hash_from_cdr` generated by
/// `zidl -b c` (and `zidl -b cpp`).
///
/// Returns 0 (ZIDL_CDR_OK) on success, non-zero on parse failure.
pub const ZzddsComputeKeyHashFn = *const fn (
    payload: [*]const u8,
    len: usize,
    hash_out: *[16]u8,
) callconv(.c) c_int;

/// Per-registration adapter.  Heap-allocated via std.heap.c_allocator when
/// zzdds_register_type_support_c is called; freed when the participant deinits.
const CKeyHashAdapter = struct {
    c_fn: ZzddsComputeKeyHashFn,

    fn computeKeyHash(ctx: *anyopaque, payload: []const u8) [16]u8 {
        const self: *CKeyHashAdapter = @ptrCast(@alignCast(ctx));
        var hash: [16]u8 = std.mem.zeroes([16]u8);
        _ = self.c_fn(payload.ptr, payload.len, &hash);
        return hash;
    }

    fn deinitAdapter(ctx: *anyopaque) void {
        const self: *CKeyHashAdapter = @ptrCast(@alignCast(ctx));
        std.heap.c_allocator.destroy(self);
    }
};

/// Register a C-ABI TypeSupport with a DomainParticipant.
///
/// @param participant          Public DDS_DomainParticipant handle.
/// @param type_name            Null-terminated type name string.
/// @param compute_key_hash_fn  C function that computes the key hash from raw
///                             CDR bytes (encap header included).  Pass NULL
///                             for keyless types.
///
/// Returns 0 on success, -1 if the internal allocation failed.
pub export fn zzdds_register_type_support_c(
    participant: DDS.DomainParticipant,
    type_name: [*:0]const u8,
    compute_key_hash_fn: ?ZzddsComputeKeyHashFn,
) callconv(.c) c_int {
    if (nil.isNil(participant)) return -1;
    const impl: *DomainParticipantImpl = @ptrCast(@alignCast(participant.ptr));
    const name = std.mem.span(type_name);

    if (compute_key_hash_fn) |c_fn| {
        const adapter = std.heap.c_allocator.create(CKeyHashAdapter) catch return -1;
        adapter.* = .{ .c_fn = c_fn };
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = adapter,
            .compute_key_hash = CKeyHashAdapter.computeKeyHash,
            .deinit = CKeyHashAdapter.deinitAdapter,
        })) {
            std.heap.c_allocator.destroy(adapter);
            return -1;
        }
    } else {
        if (!impl.registerTypeSupport(name, TypeSupport{
            .ctx = undefined,
            .compute_key_hash = struct {
                fn f(_: *anyopaque, _: []const u8) [16]u8 {
                    return std.mem.zeroes([16]u8);
                }
            }.f,
        })) return -1;
    }

    return 0;
}
