/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef COLOR_H
#define COLOR_H

#include <stdint.h>
#include <stdbool.h>

typedef enum {
    Color_RED = 0,
    Color_GREEN = 1,
    Color_BLUE = 2
} Color;

#endif /* COLOR_H */
