/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef FRAME_H
#define FRAME_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"

typedef struct Frame_s {
    uint32_t seq_num;
    char *topic;
} Frame;

#define Frame_has_key 0
int Frame_serialize(ZidlCdrWriter *_w, const Frame *_v);
int Frame_deserialize(ZidlCdrReader *_r, Frame *_v);
int Frame_skip(ZidlCdrReader *_r);

#endif /* FRAME_H */
