/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef GREETER_H
#define GREETER_H

#include <stdint.h>
#include <stdbool.h>

/* IDL interface: Greeter */
typedef struct Greeter_Vtable {
    char *(*greet)(void *ptr, char *name);
    void (*reset)(void *ptr);
    int32_t (*get_count)(void *ptr);
    void (*deinit)(void *ptr);
} Greeter_Vtable;

typedef struct Greeter {
    void                *ptr;
    const Greeter_Vtable *vtable;
} Greeter;

static inline char *Greeter_greet(Greeter _self, char *name) {
    return _self.vtable->greet(_self.ptr, name);
}

static inline void Greeter_reset(Greeter _self) {
    _self.vtable->reset(_self.ptr);
}

static inline int32_t Greeter_get_count(Greeter _self) {
    return _self.vtable->get_count(_self.ptr);
}

static inline void Greeter_deinit(Greeter _self) {
    _self.vtable->deinit(_self.ptr);
}

Greeter Greeter_zig_new(void *ptr);

#endif /* GREETER_H */
