/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef POINT_H
#define POINT_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"

typedef struct Point_s {
    int32_t x;
    int32_t y;
} Point;

#define Point_has_key 0
int Point_serialize(ZidlCdrWriter *_w, const Point *_v);
int Point_deserialize(ZidlCdrReader *_r, Point *_v);
int Point_skip(ZidlCdrReader *_r);

#endif /* POINT_H */
