/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef SAMPLE_H
#define SAMPLE_H

#include <stdint.h>
#include <stdbool.h>
#include "zidl_cdr.h"
#include "Color.h"
#include "Point.h"

#ifndef INT32_T_SEQ_DEFINED
#define INT32_T_SEQ_DEFINED
typedef struct {
    uint32_t _maximum;
    uint32_t _length;
    int32_t *_buffer;
    bool _release;
} int32_t_seq;
#endif

typedef struct Sample_s {
    uint32_t id;
    bool b;
    uint8_t u8_val;
    int16_t s16_val;
    uint16_t u16_val;
    int32_t s32_val;
    uint32_t u32_val;
    int64_t s64_val;
    uint64_t u64_val;
    float f32_val;
    double f64_val;
    char *str;
    char bstr[33];
    int32_t_seq nums;
    int32_t arr[3];
    Color clr;
    Point nested;
} Sample;

#define Sample_has_key 1
int Sample_serialize(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize(ZidlCdrReader *_r, Sample *_v);
int Sample_skip(ZidlCdrReader *_r);
int Sample_serialize_key(ZidlCdrWriter *_w, const Sample *_v);
int Sample_deserialize_key(ZidlCdrReader *_r, Sample *_v);
int Sample_compute_key_hash(const Sample *_v, uint8_t _hash[16]);

#endif /* SAMPLE_H */
