/* Generated by zidl from types.idl — DO NOT EDIT */

#include "types.h"
#include <stddef.h>

/* ── interface Greeter ── */

/* Zig DDS runtime exports (provided at link time). */
extern char *zidl_Greeter_greet(void *ptr, char *name);
extern void zidl_Greeter_reset(void *ptr);
extern int32_t zidl_Greeter_get_count(void *ptr);
extern void zidl_Greeter_deinit(void *ptr);

static const Greeter_Vtable Greeter_zig_vtable_ = {
    .greet = zidl_Greeter_greet,
    .reset = zidl_Greeter_reset,
    .get_count = zidl_Greeter_get_count,
    .deinit = zidl_Greeter_deinit,
};

Greeter Greeter_zig_new(void *ptr) {
    return (Greeter){ .ptr = ptr, .vtable = &Greeter_zig_vtable_ };
}

