/* Generated by zidl from types.idl — DO NOT EDIT */

#ifndef TYPES_ALL_H
#define TYPES_ALL_H

#include "Color.h"
#include "Point.h"
#include "Sample.h"
#include "Frame.h"
#include "Greeter.h"

#endif /* TYPES_ALL_H */
