/*
 * cyclone_pub.c — Cyclone DDS interop publisher.
 *
 * Waits for at least one matching reader (up to 5 s), writes one
 * HelloWorldData::Msg sample, then exits 0 (or exits 1 on timeout).
 *
 * Test scenario 1:  zdds_interop_sub  &  ./cyclone_pub
 * Expected result:  zdds_interop_sub receives the sample and exits 0.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "dds/dds.h"
#include "HelloWorldData.h"   /* generated by idlc */

int main(void)
{
    dds_entity_t participant, topic, publisher, writer;
    dds_qos_t   *qos;
    dds_return_t rc;

    participant = dds_create_participant(0, NULL, NULL);
    if (participant < 0) {
        fprintf(stderr, "cyclone_pub: dds_create_participant failed: %s\n",
                dds_strretcode(-participant));
        return 1;
    }

    topic = dds_create_topic(participant,
                             &HelloWorldData_Msg_desc,
                             "HelloWorldTopic",
                             NULL, NULL);
    if (topic < 0) {
        fprintf(stderr, "cyclone_pub: dds_create_topic failed: %s\n",
                dds_strretcode(-topic));
        return 1;
    }

    qos = dds_create_qos();
    dds_qset_reliability(qos, DDS_RELIABILITY_RELIABLE, DDS_SECS(1));

    publisher = dds_create_publisher(participant, NULL, NULL);
    writer    = dds_create_writer(publisher, topic, qos, NULL);
    dds_delete_qos(qos);
    if (writer < 0) {
        fprintf(stderr, "cyclone_pub: dds_create_writer failed: %s\n",
                dds_strretcode(-writer));
        return 1;
    }

    /* Wait for at least one matching reader (up to 5 s). */
    dds_publication_matched_status_t status;
    for (int i = 0; i < 50; i++) {
        dds_get_publication_matched_status(writer, &status);
        if (status.current_count > 0) break;
        dds_sleepfor(DDS_MSECS(100));
    }

    HelloWorldData_Msg msg = {
        .userID  = 42,
        .message = "Hello from Cyclone",
    };
    rc = dds_write(writer, &msg);
    if (rc != DDS_RETCODE_OK) {
        fprintf(stderr, "cyclone_pub: dds_write failed: %s\n",
                dds_strretcode(-rc));
        return 1;
    }

    printf("cyclone_pub: sent userID=%d message=\"%s\"\n",
           msg.userID, msg.message);

    dds_sleepfor(DDS_MSECS(500));
    dds_delete(participant);
    return 0;
}
