// Generated by zidl from types.idl — DO NOT EDIT

#ifndef COLOR_HPP
#define COLOR_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>

enum class Color : uint32_t {
    RED = 0,
    GREEN = 1,
    BLUE = 2
}; // enum class Color

#endif // COLOR_HPP
