// Generated by zidl from types.idl — DO NOT EDIT

#include "Frame.hpp"
#include "zidl_cdr.h"
#include <cstring>

int Frame_serialize(ZidlCdrWriter *_w, const ::Frame *_v) {
    int _rc;
    size_t _dh;
    _rc = zidl_cdr_reserve_dheader_maybe(_w, &_dh);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_u32(_w, _v->seq_num);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_string(_w, _v->topic.c_str(), (uint32_t)_v->topic.size());
    if (_rc) return _rc;
    zidl_cdr_patch_dheader_maybe(_w, _dh);
    return ZIDL_CDR_OK;
}

int Frame_deserialize(ZidlCdrReader *_r, ::Frame *_v) {
    int _rc;
    _rc = zidl_cdr_skip_dheader_if_xcdr2(_r);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_u32(_r, &_v->seq_num);
    if (_rc) return _rc;
    { const char *_sp; uint32_t _sl;
        _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl);
        if (_rc) return _rc;
        _v->topic.assign(_sp, _sl);
    }
    return ZIDL_CDR_OK;
}

int Frame_skip(ZidlCdrReader *_r) {
    int _rc;
    if (_r->xcdr_version == ZIDL_XCDR2) {
        uint32_t _size;
        _rc = zidl_cdr_read_dheader(_r, &_size);
        if (_rc) return _rc;
        return zidl_cdr_skip(_r, _size);
    }
    { uint32_t _tmp; _rc = zidl_cdr_read_u32(_r, &_tmp); if (_rc) return _rc; }
    { const char *_sp; uint32_t _sl; _rc = zidl_cdr_read_string_zerocopy(_r, &_sp, &_sl); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

