// Generated by zidl from types.idl — DO NOT EDIT

#ifndef FRAME_HPP
#define FRAME_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>
#include "zidl_cdr.h"

struct Frame {
    uint32_t seq_num{};
    std::string topic{};
}; // struct Frame

#define Frame_has_key 0
int Frame_serialize(ZidlCdrWriter *_w, const ::Frame *_v);
int Frame_deserialize(ZidlCdrReader *_r, ::Frame *_v);
int Frame_skip(ZidlCdrReader *_r);

#endif // FRAME_HPP
