// Generated by zidl from types.idl — DO NOT EDIT

#ifndef GREETER_HPP
#define GREETER_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>

class Greeter {
public:
    virtual ~Greeter() = default;
    virtual std::string greet(std::string name) = 0;
    virtual void reset() = 0;
    virtual int32_t count() const = 0;
}; // class Greeter

#endif // GREETER_HPP
