// Generated by zidl from types.idl — DO NOT EDIT

#include "Point.hpp"
#include "zidl_cdr.h"
#include <cstring>

int Point_serialize(ZidlCdrWriter *_w, const ::Point *_v) {
    int _rc;
    _rc = zidl_cdr_write_i32(_w, _v->x);
    if (_rc) return _rc;
    _rc = zidl_cdr_write_i32(_w, _v->y);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Point_deserialize(ZidlCdrReader *_r, ::Point *_v) {
    int _rc;
    _rc = zidl_cdr_read_i32(_r, &_v->x);
    if (_rc) return _rc;
    _rc = zidl_cdr_read_i32(_r, &_v->y);
    if (_rc) return _rc;
    return ZIDL_CDR_OK;
}

int Point_skip(ZidlCdrReader *_r) {
    int _rc;
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    { int32_t _tmp; _rc = zidl_cdr_read_i32(_r, &_tmp); if (_rc) return _rc; }
    return ZIDL_CDR_OK;
}

