// Generated by zidl from types.idl — DO NOT EDIT

#ifndef POINT_HPP
#define POINT_HPP

#include <cstdint>
#include <string>
#include <vector>
#include <array>
#include <stdexcept>
#include "zidl_cdr.h"

struct Point {
    int32_t x{};
    int32_t y{};
}; // struct Point

#define Point_has_key 0
int Point_serialize(ZidlCdrWriter *_w, const ::Point *_v);
int Point_deserialize(ZidlCdrReader *_r, ::Point *_v);
int Point_skip(ZidlCdrReader *_r);

#endif // POINT_HPP
