// Generated by zidl from types.idl — DO NOT EDIT

#include "types.hpp"

// ── interface Greeter ──

extern "C" {
char * zidl_Greeter_greet(void *ptr, char * name);
void zidl_Greeter_reset(void *ptr);
int32_t zidl_Greeter_get_count(void *ptr);
void zidl_Greeter_deinit(void *ptr);
}

class GreeterZigImpl : public ::Greeter {
public:
    explicit GreeterZigImpl(void *ptr) : ptr_(ptr) {}
    ~GreeterZigImpl() override { zidl_Greeter_deinit(ptr_); }

    std::string greet(std::string name) override {
        return std::string(zidl_Greeter_greet(ptr_, name.c_str()));
    }
    void reset() override {
        zidl_Greeter_reset(ptr_);
    }
    int32_t count() const override {
        return zidl_Greeter_get_count(ptr_);
    }
private:
    void *ptr_;
};

