// Generated by zidl from types.idl — DO NOT EDIT

#ifndef TYPES_ALL_HPP
#define TYPES_ALL_HPP

#include "Color.hpp"
#include "Point.hpp"
#include "Sample.hpp"
#include "Frame.hpp"
#include "Greeter.hpp"

#endif // TYPES_ALL_HPP
