//! DataWriterImpl — DCPS DataWriter implementation.
//!
//! DataWriterImpl owns a ProtocolWriter (backed by a StatefulWriter / RTPS).
//! The DDS.DataWriter vtable covers entity management and status queries.
//! Type-specific serialized writes go through writeRaw(), which is called
//! directly by the typed wrapper generated by zidl (not through the vtable).
//!
//! Write path:
//!   zidl-generated wrapper → writeRaw() → ProtocolWriter.write()
//!                          → StatefulWriter → transport

const std = @import("std");
const DDS = @import("zzdds_generated").DDS;
const nil = @import("nil.zig");
const proto = @import("../protocol/interface.zig");
const history_mod = @import("../rtps/history.zig");
const waitset = @import("waitset.zig");
const time_mod = @import("../util/time.zig");

const Guid = proto.Guid;

fn durationIsActive(d: DDS.Duration_t) bool {
    if (d.sec == 0 and d.nanosec == 0) return false;
    if (d.sec == DDS.DURATION_INFINITE_SEC and d.nanosec == DDS.DURATION_INFINITE_NSEC) return false;
    return true;
}

pub const DataWriterImpl = struct {
    alloc: std.mem.Allocator,
    topic_name: []const u8, // borrowed from TopicImpl
    type_name: []const u8, // borrowed from TopicImpl
    topic: DDS.Topic,
    publisher: DDS.Publisher,
    proto_writer: proto.ProtocolWriter,
    qos: DDS.DataWriterQos,
    listener: DDS.DataWriterListener,
    listener_mask: DDS.StatusMask,
    instance_handle: DDS.InstanceHandle_t,
    status_changes: DDS.StatusMask,
    status_cond: ?*waitset.StatusConditionImpl,

    /// Sequence number of the most recently written sample; 0 = nothing written.
    last_sn: proto.SequenceNumber = 0,

    /// Cumulative count of incompatible-QoS events; no separate mutex needed —
    /// always written from the participant's discovery callback (participant.mu held).
    incompat_total: i32 = 0,
    incompat_total_change: i32 = 0,
    incompat_last_policy: i32 = 0,

    /// PublicationMatched status counters. Written from discovery callbacks
    /// (participant.mu held); no separate writer mutex needed.
    pub_matched_total: i32 = 0,
    pub_matched_total_change: i32 = 0,
    pub_matched_current: i32 = 0,
    pub_matched_current_change: i32 = 0,
    pub_matched_last_handle: DDS.InstanceHandle_t = 0,

    /// Cumulative count of offered-deadline-missed events; written from
    /// participant.checkTimers() (participant.mu held).
    deadline_missed_total: i32 = 0,
    deadline_missed_total_change: i32 = 0,

    /// Cumulative count of liveliness-lost events; written from
    /// participant.checkTimers() (participant.mu held).
    liveliness_lost_total: i32 = 0,
    liveliness_lost_total_change: i32 = 0,

    /// Clock used for deadline and liveliness interval timers.
    timer_clock: time_mod.Clock,

    /// Monotonic timestamp of the last successful write; used by DEADLINE/LIVELINESS checks.
    /// Initialized to creation time so the first deadline window starts at entity creation.
    last_write_ns: std.atomic.Value(i64),

    /// Monotonic timestamp of the last liveliness assertion; reset by write() for
    /// AUTOMATIC kind and by assert_liveliness() for MANUAL kinds.
    liveliness_last_ns: std.atomic.Value(i64),

    const Self = @This();

    pub fn init(
        alloc: std.mem.Allocator,
        topic: DDS.Topic,
        publisher: DDS.Publisher,
        proto_writer: proto.ProtocolWriter,
        qos: DDS.DataWriterQos,
        listener: DDS.DataWriterListener,
        mask: DDS.StatusMask,
        instance_handle: DDS.InstanceHandle_t,
        timer_clock: time_mod.Clock,
    ) !*Self {
        const now = timer_clock.nowNs();
        const self = try alloc.create(Self);
        self.* = .{
            .alloc = alloc,
            .topic_name = topic.get_name(),
            .type_name = topic.get_type_name(),
            .topic = topic,
            .publisher = publisher,
            .proto_writer = proto_writer,
            .qos = .{},
            .listener = listener,
            .listener_mask = mask,
            .instance_handle = instance_handle,
            .status_changes = 0,
            .status_cond = null,
            .timer_clock = timer_clock,
            .last_write_ns = .init(now),
            .liveliness_last_ns = .init(now),
        };
        self.qos = try qos.clone(alloc);
        // Wire up the StatusCondition.
        const sc = try waitset.StatusConditionImpl.init(
            alloc,
            self.toEntity(),
            getStatusFn,
        );
        self.status_cond = sc;
        return self;
    }

    pub fn deinit(self: *Self) void {
        if (self.status_cond) |sc| sc.deinit();
        self.qos.deinit(self.alloc);
        // NOTE: proto_writer lifecycle is owned by the participant (via
        // pubDestroyProtoWriter callback), not by DataWriterImpl.
        self.alloc.destroy(self);
    }

    /// Write a pre-serialized CDR payload (4-byte encap header + CDR bytes).
    /// Called by the zidl-generated typed wrapper.
    pub fn writeRaw(
        self: *Self,
        kind: history_mod.ChangeKind,
        source_timestamp: history_mod.RtpsTimestamp,
        instance_handle: history_mod.InstanceHandle,
        key_hash: [16]u8,
        data: []const u8,
    ) !history_mod.SequenceNumber {
        // RESOURCE_LIMITS enforcement (max_samples for keyless topics, where
        // max_samples_per_instance == max_samples since there is one instance).
        // 0 means unlimited; only enforce whichever limits are active (> 0).
        const ms = self.qos.resource_limits.max_samples;
        const msi = self.qos.resource_limits.max_samples_per_instance;
        const max: i32 = if (ms > 0 and msi > 0) @min(ms, msi) else if (ms > 0) ms else if (msi > 0) msi else 0;
        if (max > 0) {
            const limit: usize = @intCast(max);
            if (self.proto_writer.cacheLen() >= limit) {
                if (self.qos.reliability.kind == .BEST_EFFORT_RELIABILITY_QOS) {
                    return error.OutOfResources;
                }
                // RELIABLE: poll until space frees up (1 ms sleep, 10 s timeout).
                const deadline_ns = time_mod.nanoTimestamp() + 10 * std.time.ns_per_s;
                while (self.proto_writer.cacheLen() >= limit) {
                    if (time_mod.nanoTimestamp() >= deadline_ns)
                        return error.Timeout;
                    time_mod.sleepNs(1 * std.time.ns_per_ms);
                }
            }
        }

        const sn = try self.proto_writer.write(kind, source_timestamp, instance_handle, key_hash, data);
        self.last_sn = sn;
        const now_ns = self.timer_clock.nowNs();
        self.last_write_ns.store(now_ns, .monotonic);
        // AUTOMATIC: any write() counts as a liveliness assertion.
        // MANUAL_BY_PARTICIPANT: only participant.assert_liveliness() counts.
        // MANUAL_BY_TOPIC: only writer.assert_liveliness() counts.
        if (self.qos.liveliness.kind == .AUTOMATIC_LIVELINESS_QOS) {
            self.liveliness_last_ns.store(now_ns, .monotonic);
        }
        return sn;
    }

    /// Returns true when all RELIABLE matched readers have acked up to last_sn.
    pub fn allAcked(self: *Self) bool {
        return self.proto_writer.allAcked(self.last_sn);
    }

    pub fn matchedReaderCount(self: *Self) usize {
        return self.proto_writer.matchedReaderCount();
    }

    /// Compute a stable DDS instance handle from a 16-byte key hash.
    /// For keyless types the key hash is all zeros; all calls return the same handle.
    pub fn registerInstanceRaw(key_hash: [16]u8) DDS.InstanceHandle_t {
        return keyHashToHandle(key_hash);
    }

    /// Send a NOT_ALIVE_DISPOSED change for the given instance.
    /// Does not update deadline/liveliness timestamps (lifecycle, not data).
    pub fn disposeRaw(
        self: *Self,
        source_timestamp: history_mod.RtpsTimestamp,
        instance_handle: history_mod.InstanceHandle,
        key_hash: [16]u8,
    ) !void {
        _ = try self.proto_writer.write(
            .not_alive_disposed,
            source_timestamp,
            instance_handle,
            key_hash,
            &.{},
        );
    }

    /// Send a NOT_ALIVE_UNREGISTERED change (or NOT_ALIVE_DISPOSED if autodispose is set).
    /// Does not update deadline/liveliness timestamps (lifecycle, not data).
    pub fn unregisterRaw(
        self: *Self,
        source_timestamp: history_mod.RtpsTimestamp,
        instance_handle: history_mod.InstanceHandle,
        key_hash: [16]u8,
    ) !void {
        const kind: history_mod.ChangeKind = if (self.qos.writer_data_lifecycle.autodispose_unregistered_instances)
            .not_alive_disposed
        else
            .not_alive_unregistered;
        _ = try self.proto_writer.write(kind, source_timestamp, instance_handle, key_hash, &.{});
    }

    pub fn toDDSDataWriter(self: *Self) DDS.DataWriter {
        return .{ .ptr = self, .vtable = &vtable };
    }

    fn toEntity(self: *Self) DDS.Entity {
        return .{ .ptr = self, .vtable = &entity_vtable };
    }

    /// Called by participant when a remote DataReader matches or unmatches this writer.
    /// Updates PublicationMatched counters and fires on_publication_matched if registered.
    /// May be called while participant.mu is held; must not re-enter participant.
    pub fn notifyPublicationMatched(ctx: *anyopaque, remote_handle: DDS.InstanceHandle_t, added: bool) void {
        const self: *Self = @ptrCast(@alignCast(ctx));
        if (added) self.pub_matched_total += 1;
        self.pub_matched_total_change += if (added) 1 else 0;
        const delta: i32 = if (added) 1 else -1;
        self.pub_matched_current += delta;
        self.pub_matched_current_change += delta;
        self.pub_matched_last_handle = remote_handle;
        self.status_changes |= DDS.PUBLICATION_MATCHED_STATUS;
        if (self.status_cond) |sc| sc.notifyWakeup();

        if (self.listener_mask & DDS.PUBLICATION_MATCHED_STATUS != 0) {
            const status = DDS.PublicationMatchedStatus{
                .total_count = self.pub_matched_total,
                .total_count_change = if (added) 1 else 0,
                .current_count = self.pub_matched_current,
                .current_count_change = delta,
                .last_subscription_handle = remote_handle,
            };
            self.status_changes &= ~DDS.PUBLICATION_MATCHED_STATUS;
            self.pub_matched_total_change = 0;
            self.pub_matched_current_change = 0;
            if (self.listener.on_publication_matched) |cb| cb(self.toDDSDataWriter(), &status, self.listener.listener_data);
        }
    }

    /// Called by participant when a discovered remote reader's QoS is incompatible
    /// with this writer's offered QoS (DDS v1.4 §2.2.4.3).
    /// Updates counters and fires on_offered_incompatible_qos if registered.
    /// May be called while participant.mu is held; must not re-enter participant.
    pub fn notifyIncompatibleQos(ctx: *anyopaque, policy_id: i32) void {
        const self: *Self = @ptrCast(@alignCast(ctx));
        self.incompat_total += 1;
        self.incompat_total_change += 1;
        self.incompat_last_policy = policy_id;
        self.status_changes |= DDS.OFFERED_INCOMPATIBLE_QOS_STATUS;
        if (self.status_cond) |sc| sc.notifyWakeup();

        if (self.listener_mask & DDS.OFFERED_INCOMPATIBLE_QOS_STATUS != 0) {
            var status = DDS.OfferedIncompatibleQosStatus{};
            status.total_count = self.incompat_total;
            status.total_count_change = 1;
            status.last_policy_id = policy_id;
            self.incompat_total_change = 0;
            self.status_changes &= ~DDS.OFFERED_INCOMPATIBLE_QOS_STATUS;
            if (self.listener.on_offered_incompatible_qos) |cb| cb(self.toDDSDataWriter(), &status, self.listener.listener_data);
        }
    }

    /// Fire on_offered_deadline_missed if the listener is registered for it.
    /// May be called while participant.mu is held; must not re-enter participant.
    pub fn notifyDeadlineMissed(self: *Self) void {
        self.deadline_missed_total += 1;
        self.deadline_missed_total_change += 1;
        self.status_changes |= DDS.OFFERED_DEADLINE_MISSED_STATUS;
        if (self.status_cond) |sc| sc.notifyWakeup();
        if (self.listener_mask & DDS.OFFERED_DEADLINE_MISSED_STATUS != 0) {
            var status = DDS.OfferedDeadlineMissedStatus{};
            status.total_count = self.deadline_missed_total;
            status.total_count_change = 1;
            self.deadline_missed_total_change = 0;
            self.status_changes &= ~DDS.OFFERED_DEADLINE_MISSED_STATUS;
            if (self.listener.on_offered_deadline_missed) |cb| cb(self.toDDSDataWriter(), &status, self.listener.listener_data);
        }
    }

    /// Fire on_liveliness_lost if the listener is registered for it.
    /// May be called while participant.mu is held; must not re-enter participant.
    pub fn notifyLivelinessLost(self: *Self) void {
        self.liveliness_lost_total += 1;
        self.liveliness_lost_total_change += 1;
        self.status_changes |= DDS.LIVELINESS_LOST_STATUS;
        if (self.status_cond) |sc| sc.notifyWakeup();
        if (self.listener_mask & DDS.LIVELINESS_LOST_STATUS != 0) {
            var status = DDS.LivelinessLostStatus{};
            status.total_count = self.liveliness_lost_total;
            status.total_count_change = 1;
            self.liveliness_lost_total_change = 0;
            self.status_changes &= ~DDS.LIVELINESS_LOST_STATUS;
            if (self.listener.on_liveliness_lost) |cb| cb(self.toDDSDataWriter(), &status, self.listener.listener_data);
        }
    }

    /// Called by participant.checkTimers() for each active writer.
    /// Checks DEADLINE and LIVELINESS; fires notifications when thresholds are exceeded.
    /// Called while participant.mu is held; must not re-enter participant.
    pub fn checkTimersFn(ctx: *anyopaque, now_ns: i64) void {
        const self: *Self = @ptrCast(@alignCast(ctx));

        const dl = self.qos.deadline.period;
        if (durationIsActive(dl)) {
            const period_ns = @as(i64, dl.sec) * std.time.ns_per_s + @as(i64, dl.nanosec);
            const last = self.last_write_ns.load(.monotonic);
            if (now_ns - last >= period_ns) {
                self.last_write_ns.store(now_ns, .monotonic);
                self.notifyDeadlineMissed();
            }
        }

        const ll = self.qos.liveliness.lease_duration;
        if (durationIsActive(ll)) {
            const lease_ns = @as(i64, ll.sec) * std.time.ns_per_s + @as(i64, ll.nanosec);
            const last = self.liveliness_last_ns.load(.monotonic);
            if (now_ns - last >= lease_ns) {
                self.liveliness_last_ns.store(now_ns, .monotonic);
                self.notifyLivelinessLost();
            }
        }
    }

    /// Called by participant.vtAssertLiveliness() to assert liveliness for
    /// AUTOMATIC and MANUAL_BY_PARTICIPANT writers.
    pub fn assertLivelinessFn(ctx: *anyopaque) void {
        const self: *Self = @ptrCast(@alignCast(ctx));
        if (self.qos.liveliness.kind == .MANUAL_BY_TOPIC_LIVELINESS_QOS) return;
        self.liveliness_last_ns.store(self.timer_clock.nowNs(), .monotonic);
    }

    // ── Entity vtable (shared subset) ────────────────────────────────────────

    const entity_vtable = DDS.Entity.Vtable{
        .enable = vtEnable,
        .get_statuscondition = vtGetStatusCond,
        .get_status_changes = vtGetStatusChanges,
        .get_instance_handle = vtGetHandle,
        .deinit = vtDeinit,
    };

    // ── DDS.DataWriter vtable ─────────────────────────────────────────────────

    const vtable = DDS.DataWriter.Vtable{
        .enable = vtEnable,
        .get_statuscondition = vtGetStatusCond,
        .get_status_changes = vtGetStatusChanges,
        .get_instance_handle = vtGetHandle,
        .set_qos = vtSetQos,
        .get_qos = vtGetQos,
        .set_listener = vtSetListener,
        .get_listener = vtGetListener,
        .get_topic = vtGetTopic,
        .get_publisher = vtGetPublisher,
        .wait_for_acknowledgments = vtWaitForAck,
        .get_liveliness_lost_status = vtGetLivelinessLost,
        .get_offered_deadline_missed_status = vtGetDeadlineMissed,
        .get_offered_incompatible_qos_status = vtGetIncompatQos,
        .get_publication_matched_status = vtGetPubMatched,
        .assert_liveliness = vtAssertLiveliness,
        .get_matched_subscriptions = vtGetMatchedSubs,
        .get_matched_subscription_data = vtGetMatchedSubData,
        .deinit = vtDeinit,
    };

    fn vtEnable(_: *anyopaque) DDS.ReturnCode_t {
        return DDS.RETCODE_OK;
    }

    fn vtGetStatusCond(ctx: *anyopaque) DDS.StatusCondition {
        const self = cast(ctx);
        if (self.status_cond) |sc| return sc.toDDSStatusCondition();
        return nil.nil_status_condition;
    }

    fn vtGetStatusChanges(ctx: *anyopaque) DDS.StatusMask {
        return cast(ctx).status_changes;
    }

    fn vtGetHandle(ctx: *anyopaque) DDS.InstanceHandle_t {
        return cast(ctx).instance_handle;
    }

    fn vtSetQos(ctx: *anyopaque, qos: *const DDS.DataWriterQos) DDS.ReturnCode_t {
        const self = cast(ctx);
        const new_qos = qos.clone(self.alloc) catch return DDS.RETCODE_OUT_OF_RESOURCES;
        self.qos.deinit(self.alloc);
        self.qos = new_qos;
        return DDS.RETCODE_OK;
    }

    fn vtGetQos(ctx: *anyopaque, qos: *DDS.DataWriterQos) DDS.ReturnCode_t {
        qos.* = cast(ctx).qos;
        return DDS.RETCODE_OK;
    }

    fn vtSetListener(ctx: *anyopaque, a_listener: ?*const DDS.DataWriterListener, mask: DDS.StatusMask) DDS.ReturnCode_t {
        const self = cast(ctx);
        self.listener = if (a_listener) |l| l.* else DDS.noop_DataWriterListener;
        self.listener_mask = mask;
        return DDS.RETCODE_OK;
    }

    fn vtGetListener(ctx: *anyopaque) DDS.DataWriterListener {
        return cast(ctx).listener;
    }

    fn vtGetTopic(ctx: *anyopaque) DDS.Topic {
        return cast(ctx).topic;
    }

    fn vtGetPublisher(ctx: *anyopaque) DDS.Publisher {
        return cast(ctx).publisher;
    }

    fn vtWaitForAck(ctx: *anyopaque, timeout: *const DDS.Duration_t) DDS.ReturnCode_t {
        const self = cast(ctx);
        if (self.qos.reliability.kind == .BEST_EFFORT_RELIABILITY_QOS) return DDS.RETCODE_OK;
        if (self.last_sn == 0) return DDS.RETCODE_OK;

        const POLL_NS: u64 = 1_000_000; // 1 ms
        const deadline_ns: ?i64 = if (timeout.sec == DDS.DURATION_INFINITE_SEC and
            timeout.nanosec == DDS.DURATION_INFINITE_NSEC)
            null
        else blk: {
            const now = time_mod.nanoTimestamp();
            break :blk now +
                @as(i64, timeout.sec) * std.time.ns_per_s +
                @as(i64, timeout.nanosec);
        };

        while (true) {
            if (self.proto_writer.allAcked(self.last_sn)) return DDS.RETCODE_OK;
            if (deadline_ns) |dl| {
                if (time_mod.nanoTimestamp() >= dl) return DDS.RETCODE_TIMEOUT;
            }
            time_mod.sleepNs(POLL_NS);
        }
    }

    fn vtGetLivelinessLost(ctx: *anyopaque, status: *DDS.LivelinessLostStatus) DDS.ReturnCode_t {
        const self = cast(ctx);
        status.* = .{
            .total_count = self.liveliness_lost_total,
            .total_count_change = self.liveliness_lost_total_change,
        };
        self.liveliness_lost_total_change = 0;
        self.status_changes &= ~DDS.LIVELINESS_LOST_STATUS;
        return DDS.RETCODE_OK;
    }

    fn vtGetDeadlineMissed(ctx: *anyopaque, status: *DDS.OfferedDeadlineMissedStatus) DDS.ReturnCode_t {
        const self = cast(ctx);
        status.* = .{
            .total_count = self.deadline_missed_total,
            .total_count_change = self.deadline_missed_total_change,
        };
        self.deadline_missed_total_change = 0;
        self.status_changes &= ~DDS.OFFERED_DEADLINE_MISSED_STATUS;
        return DDS.RETCODE_OK;
    }

    fn vtGetIncompatQos(ctx: *anyopaque, status: *DDS.OfferedIncompatibleQosStatus) DDS.ReturnCode_t {
        const self: *Self = @ptrCast(@alignCast(ctx));
        status.* = .{
            .total_count = self.incompat_total,
            .total_count_change = self.incompat_total_change,
            .last_policy_id = self.incompat_last_policy,
        };
        self.incompat_total_change = 0;
        self.status_changes &= ~DDS.OFFERED_INCOMPATIBLE_QOS_STATUS;
        return DDS.RETCODE_OK;
    }

    fn vtGetPubMatched(ctx: *anyopaque, status: *DDS.PublicationMatchedStatus) DDS.ReturnCode_t {
        const self = cast(ctx);
        status.* = .{
            .total_count = self.pub_matched_total,
            .total_count_change = self.pub_matched_total_change,
            .current_count = self.pub_matched_current,
            .current_count_change = self.pub_matched_current_change,
            .last_subscription_handle = self.pub_matched_last_handle,
        };
        self.pub_matched_total_change = 0;
        self.pub_matched_current_change = 0;
        self.status_changes &= ~DDS.PUBLICATION_MATCHED_STATUS;
        return DDS.RETCODE_OK;
    }

    fn vtAssertLiveliness(ctx: *anyopaque) DDS.ReturnCode_t {
        const self = cast(ctx);
        self.liveliness_last_ns.store(self.timer_clock.nowNs(), .monotonic);
        return DDS.RETCODE_OK;
    }

    fn vtGetMatchedSubs(ctx: *anyopaque, handles: ?*DDS.InstanceHandleSeq) DDS.ReturnCode_t {
        const seq = handles orelse return DDS.RETCODE_BAD_PARAMETER;
        const self = cast(ctx);
        var guids: std.ArrayListUnmanaged(Guid) = .empty;
        defer guids.deinit(self.alloc);
        self.proto_writer.listMatchedReaders(self.alloc, &guids) catch
            return DDS.RETCODE_OUT_OF_RESOURCES;
        seq.* = .{};
        const n = guids.items.len;
        if (n == 0) return DDS.RETCODE_OK;
        const buf = self.alloc.alloc(DDS.InstanceHandle_t, n) catch return DDS.RETCODE_OUT_OF_RESOURCES;
        for (guids.items, 0..) |guid, i| buf[i] = guidToHandle(guid);
        seq._buffer = buf.ptr;
        seq._length = @intCast(n);
        seq._maximum = @intCast(n);
        seq._release = true;
        return DDS.RETCODE_OK;
    }

    fn vtGetMatchedSubData(ctx: *anyopaque, data: *DDS.SubscriptionBuiltinTopicData, handle: DDS.InstanceHandle_t) DDS.ReturnCode_t {
        const self = cast(ctx);
        var guids: std.ArrayListUnmanaged(Guid) = .empty;
        defer guids.deinit(self.alloc);
        self.proto_writer.listMatchedReaders(self.alloc, &guids) catch
            return DDS.RETCODE_BAD_PARAMETER;
        for (guids.items) |guid| {
            if (guidToHandle(guid) == handle) {
                data.* = .{};
                data.key = guidToBuiltinKey(guid);
                data.topic_name = self.topic_name;
                data.type_name = self.type_name;
                return DDS.RETCODE_OK;
            }
        }
        return DDS.RETCODE_BAD_PARAMETER;
    }

    fn vtDeinit(ctx: *anyopaque) void {
        cast(ctx).deinit();
    }

    // ── status helper for StatusConditionImpl ─────────────────────────────────

    fn getStatusFn(entity_ptr: *anyopaque) DDS.StatusMask {
        return cast(entity_ptr).status_changes;
    }

    fn cast(ctx: *anyopaque) *Self {
        return @ptrCast(@alignCast(ctx));
    }
};

// ── GUID helpers ──────────────────────────────────────────────────────────────

/// FNV-1a hash of a 16-byte key hash → nonzero positive i32 instance handle.
/// For keyless topics the key hash is all zeros; all calls return the same handle.
pub fn keyHashToHandle(key_hash: [16]u8) DDS.InstanceHandle_t {
    var h: u32 = 2166136261;
    for (key_hash) |b| {
        h ^= b;
        h *%= 16777619;
    }
    const v: i32 = @intCast(h & 0x7FFF_FFFF);
    return if (v == 0) 1 else v;
}

/// FNV-1a hash of a GUID's 16 bytes → nonzero positive i32 instance handle.
pub fn guidToHandle(guid: Guid) DDS.InstanceHandle_t {
    const bytes = std.mem.asBytes(&guid);
    var h: u32 = 2166136261;
    for (bytes) |b| {
        h ^= b;
        h *%= 16777619;
    }
    // Ensure nonzero and positive (i32 range).
    const v: i32 = @intCast(h & 0x7FFF_FFFF);
    return if (v == 0) 1 else v;
}

/// First 12 bytes of GUID (GuidPrefix) as a BuiltinTopicKey_t.
pub fn guidToBuiltinKey(guid: Guid) DDS.BuiltinTopicKey_t {
    const bytes = &guid.prefix.bytes;
    return .{ .value = .{
        @as(i32, @bitCast(@as(u32, bytes[0]) | @as(u32, bytes[1]) << 8 | @as(u32, bytes[2]) << 16 | @as(u32, bytes[3]) << 24)),
        @as(i32, @bitCast(@as(u32, bytes[4]) | @as(u32, bytes[5]) << 8 | @as(u32, bytes[6]) << 16 | @as(u32, bytes[7]) << 24)),
        @as(i32, @bitCast(@as(u32, bytes[8]) | @as(u32, bytes[9]) << 8 | @as(u32, bytes[10]) << 16 | @as(u32, bytes[11]) << 24)),
    } };
}
